### ISSUE TITLE
Add Example for interacting Components/Systems

### ISSUE THREAD

**Issue by JerkyTreats** [Unity-Technologies/EntityComponentSystemSamples#104]
HelloCubes give a good example of 1-2 components interacting with independent systems.

Boids gives a complex example of dozens of components interacting with dozens of related systems.

Can we get an example somewhere in the middle, showing a few components interacting with related systems (ie. the output of one job is needed before another job)? 

I feel the jump from HelloCube to Boids is a bit steep.

**Comment by MostHated** [comment]
👍 +1 on this.

**Comment by leethomason** [comment]
This is being tracked internally as 1160284. Closing external issue. Thanks for reporting (and I've thought the same think about the rather steep jump.)
