### ISSUE TITLE
Add Example for VR projects

### ISSUE THREAD

**Issue by castana1962** [Unity-Technologies/EntityComponentSystemSamples#105]
Hi
Since I am working with VR projects and the biggest problem is the VR Performance, for it, Could you add any VR project done with ECS? Would it be possible?
Thanks
Alejandro

**Comment by davidv-unity** [comment]
Hi Alejandro,

We will provide further samples in the future and we recently released the MegaCity project (https://unity.com/megacity) which is focused on streaming, culling and LODs which might be what you are looking for.

If that does not help you, do you have an example where you are cpu bound in VR (only) where you would like to have a reference project where this is solved using dots/ecs? As from my experience games in VR are usually GPU bound (so dots will not help much right now) or cpu bound - where usually the "non VR" versions of the game face the same issue, so all the released examples should be applicable. If that does not help, feel free to reopen the issue with a small comment.
Kind regards!

**Comment by castana1962** [comment]
Hi davidv-unity
I am trying with Megacity demo and I am interested in adding the SteamVR plugin in this one  prijact to see it in my Oculus(Rify/Go) and HTC Vive but I am having any problem and I cannot fix it yet, more info here
https://forum.unity.com/threads/cannot-set-field-of-view-on-camera-with-name-playercam-while-vr-is-enabled-in-megacity-demo.648031/
I know that VR requires a lot GPU but my biggest problem is the Performance of my PC 3D Assets and since I know that Megacity was done for mobile purposes and like the VR has similar Performance developing), I am interested in using it( DOTS) to optimize these PC 3D assets for VR projects,
Hopefully you can understand me and sorry for my little English
Thanks for your time
Alejandro

**Comment by davidv-unity** [comment]
Hi, I looked at your post and this does not seem to be related to DOTS.
If you are new to VR development I suggest following [this tutorial](https://unity3d.com/learn/tutorials/topics/xr/getting-started-vr-development).

Regarding your question here: do I understand you correctly that you are interested in simplifying you meshes using DOTS? 
For this case DOTS could indeed help but as you only need to do this once ("offline") I suggest you look into other solutions except when it's for the joy of learning. We are looking into providing new `IJob` types that reduce the overhead when working with meshes, but there is no fixed release date yet.

**Comment by castana1962** [comment]
Hi
Thanks for the info 
On the other hand ans since I am new in ECS and like I am interested in learning about  How I could create an IJob types that reduce the overhead when working with meshes, for it and if it is possible, Could you get some info about this topic?  Since I need to fix this problem, I will work hardly to try to do it in Unity ECS or Could you let me get some contact to get any advice? Would it be possible?
Thanks for your time
Alejandro

**Comment by davidv-unity** [comment]
Alright, sure. The job types we provide are basically (optimized) versions of data transformations we encounter on a regular basis. Think of it as building blocks. It depends on which level of granularity you need but you should always choose the highest level of abstraction (as it reduces boilerplate code and we can optimize the implementations of thos further, so your code _could_ get feaster when upgrading to a new version without changing it). From there it really depends on what you actually want to achieve. [This](https://docs.unity3d.com/Packages/com.unity.entities@0.0/manual/chunk_iteration_job.html) might be a good starting point for you as it shows you how to get direct access to the underlying buffers. If `IJobProcessComponentData(WithEntity)` is not suited for your needs, check if `IJobParallelFor` is fine. If you would need something completely else, you can always implement the raw `IJob` interface directly. Check out the [MegaCity](https://unity.com/megacity) example to see the different types "in action". Hope that helps!

**Comment by castana1962** [comment]
Hi davidv-unity
I am starting with Megacity demo and very excited for it, but it is a very ECS complex project for me. If you could add some Tutorial Videos about Megacity, I think that all of use could learn better and it would be great !!!
Thanks a lot for your help !!!
Best Regards
Alejandro

**Comment by davidv-unity** [comment]
Hi castana1962,
As above, you can find all of this at the [MegaCity](https://unity.com/megacity) page (*Building the Megacity* section). There are currently 8 videos linked that should get you started.
Feel free to use the forum for any questions you got 🙂 Kind regards.
