### ISSUE TITLE
what does JobHandle.CombineDependencies do ?

### ISSUE THREAD

**Issue by Al-Asl** [Unity-Technologies/EntityComponentSystemSamples#106]
I want to ask some question about the boid example because the lake of documentation :

- what JobHandle.CombineDependencies do and when to use it ?
- why did we pass JobHandle to ComponentGroup as in :
 m_BoidGroup.AddDependency(inputDeps); in BoidSystem.cs

**Comment by joeante** [comment]
Please ask on the forum.
