### ISSUE TITLE
Burst

### ISSUE THREAD

**Issue by mrchenyg** [Unity-Technologies/EntityComponentSystemSamples#107]

**Comment by mrchenyg** [comment]
![image](https://user-images.githubusercontent.com/22088817/53610374-8d061580-3c05-11e9-9017-198df2f2a1fe.png)

![image](https://user-images.githubusercontent.com/22088817/53610352-765fbe80-3c05-11e9-992c-9a453213943f.png)

**Comment by davidv-unity** [comment]
Hey and thanks for filing an issue for this. It should be fixed now with the current versions, please reopen the issue with a small description if you still encounter errors.
