### ISSUE TITLE
Bool still not working with IComponentData

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/EntityComponentSystemSamples#108]
Currently Boolean can't be used in IComponentData and I was told to fill an issue here by a dev working on Unity.Mathematics.

[See the Unity.Mathematics thread.](https://github.com/Unity-Technologies/Unity.Mathematics/issues/57)
[See the Unity Forums thread.](https://forum.unity.com/threads/bool1-gone-in-preview-4.532814/)
[See this question that got nowhere.](https://github.com/Unity-Technologies/EntityComponentSystemSamples/issues/63)

Sorry for the obvious duplicate but after several months I consider this an omission, so here's a reminder :) 

Cheers.

**Comment by MostHated** [comment]
I know it's not the same, but there is a workaround if you need it to just work asap.

`[Serializable]
    public struct Bool
    {
        [SerializeField] private byte Value;

        public static implicit operator Bool(bool b) => new Bool() {Value = Convert.ToByte(b)};
        public static implicit operator bool(Bool b) => b.Value == 1;

        public override string ToString() => Value == 1 ? "true" : "false";
        public override int GetHashCode() => Value.GetHashCode();
    }

#if UNITY_EDITOR
    [CustomPropertyDrawer(typeof(Bool))]
    public class BlittableBoolDrawer : PropertyDrawer
    {
        public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
        {
            EditorGUI.BeginProperty(position, label, property);
            property.Next(true);
            property.intValue = (EditorGUI.Toggle(position, label, property.intValue == 1 ? true : false) ? 1 : 0);
            EditorGUI.EndProperty();
        }
    }
#endif`

**Comment by AlexandreFiset** [comment]
I tried that and it throws errors in the console in the latest version of Unity 2019.1 and latest Entities + Mathematics packages :( What I do is use a 0-1 int...

**Comment by MostHated** [comment]
Ah, I have not personally tried it with 2019.1, so I am not sure if there is a difference there. I had been using it with 2018.3, entities preview .23

**Comment by StewMcc** [comment]
- Unity  2019.1.0f2:
 - com.unity.entities@0.0.12-preview.30
 - com.unity.mathematics@1.0.0-preview.1

No longer needed the workaround above, bool works in Jobs/IComponentData fine now it seems.

**Comment by leethomason** [comment]
Excellent that it is working; closing bug pending further issues.
