### ISSUE TITLE
How to read SharedComponentData in IJobChunk?

### ISSUE THREAD

**Issue by SetoKaiba** [Unity-Technologies/EntityComponentSystemSamples#109]
I try to make a chunk iteration with IJobChunk with SharedComponentData. But I found that I can't, because I can't get access to EntityManager in a Job.

https://gist.github.com/SetoKaiba/c323ac39775023d3992132eb4072a6a7

**Comment by integer222** [comment]
У меня так работает

`
var em = World.Active.GetExistingManager<EntityManager>();
chunk.GetSharedComponentData(TestSharedComponentDataType, em)`

**Comment by SetoKaiba** [comment]
> System.NotSupportedException: The managed class type `Unity.Entities.World` is not supported. Loading from a static field `Unity.Entities.World Unity.Entities.World::<Active>k__BackingField` is not supported by burst



Thank you. I can use World.Active.EntityManager.
But I can't use burst compile for it.
I may not use BurstCompile in development for debug purpose.
But I will use it in production.

**Comment by SetoKaiba** [comment]
Updated the gist.
But in the deprecated injection style. I can use IJobParallelFor.
And I can use burst compile for it.
Remove the debug string related code.

**Comment by SetoKaiba** [comment]
Is there a way to iterate entities in jobs with the same archetype in new style with burst compile?

**Comment by leethomason** [comment]
@SetoKaiba questions on the best approach are probably best on the Unity forum, since it isn't an issue in the example code.
