### ISSUE TITLE
Unity packages error

### ISSUE THREAD

**Issue by zzjfengqing** [Unity-Technologies/EntityComponentSystemSamples#11]
C:/ProgramData/Unity/cache/packages/staging-packages.unity.com/com.unity.burst@0.2.1/Editor/BurstReflection.cs(19,67): error CS0246: The type or namespace name `AssembliesType' could not be found. Are you missing an assembly reference?

C:/ProgramData/Unity/cache/packages/staging-packages.unity.com/com.unity.burst@0.2.1/Editor/BurstReflection.cs(155,73): error CS0246: The type or namespace name `AssembliesType' could not be found. Are you missing an assembly reference?

C:/ProgramData/Unity/cache/packages/staging-packages.unity.com/com.unity.collections@0.0.8/Unity.Collections/NativeHashMap.cs(602,14): error CS0246: The type or namespace name `NativeSetThreadIndex' could not be found. Are you missing an assembly reference?

C:/ProgramData/Unity/cache/packages/staging-packages.unity.com/com.unity.collections@0.0.8/Unity.Collections/NativeHashMap.cs(794,14): error CS0246: The type or namespace name `NativeSetThreadIndex' could not be found. Are you missing an assembly reference?

C:/ProgramData/Unity/cache/packages/staging-packages.unity.com/com.unity.collections@0.0.8/Unity.Collections/NativeQueue.cs(323,8): error CS0246: The type or namespace name `NativeSetThreadIndex' could not be found. Are you missing an assembly reference?

When I open this samples project in Unity2018.1.0b13, editor give me five error.

**Comment by raxashafique** [comment]
Same for me, can't seem to fix it either.
Would love to try it all.
These errors occur in all the ECS/Job System projects on git.
Any workaround would be much appreciated.

**Comment by cg4213** [comment]
Same for me, using a b13 unity on Mac
anyone try it on a b12?

**Comment by cg4213** [comment]
I looked around a bit.there is a preview version of unity that can run this demo.i did not try it yet
https://beta.unity3d.com/download/ed1bf90b40e6/public_download.html

**Comment by edencakir** [comment]
Same here, haven't tried the b12 yet.

**Comment by zzjfengqing** [comment]
I download the b12 version form the link above,but it not work！ same error occour!

**Comment by MrSwistak** [comment]
same problem here

**Comment by ArnaudValensi** [comment]
Same here :'(

**Comment by haoRchen** [comment]
the preview build posted by @cg4213 will be able to run the sample projects. If you have Unity Hub, make sure you delete the existing b12 and link the preview b12 version!

**Comment by MartinGram** [comment]
Issue has been solved with using the correct build found here: https://beta.unity3d.com/download/ed1bf90b40e6/public_download.html

**Comment by ekrem007** [comment]
### **Reimport All fixed same problem for me )**
