### ISSUE TITLE
Request to use AnimationCurve in job system.

### ISSUE THREAD

**Issue by watsonsong** [Unity-Technologies/EntityComponentSystemSamples#110]
It is useful to use AnimationCurve, especial when I need to implement something like particle system which heavy depend on the curve.
I find the solution like here:
https://github.com/5argon/E7Unity/blob/master/SampledAnimationCurve/SampledAnimationCurve.cs

But I think it not a final resolution, first it use a NativeArray to simulate the AnimationCurve, it may missing some value if there has a lot of keyframes. Another problem is NativeArray can not nested into another NativeArray, so it hard to put the AnimationCurve as a component data.

Is there any good way to deal with AnimationCurve?

**Comment by joeante** [comment]
Currently no. but we are planning to add blob data that could solve these use cases.
