### ISSUE TITLE
Packages fail to bump on 2018.3.7f1

### ISSUE THREAD

**Issue by JerkyTreats** [Unity-Technologies/EntityComponentSystemSamples#113]
Moving up to 2018.3.7f1 breaks packages, resulting in totally broken Samples project. 

If I have time Ill see if I can hack around `manifest.json` to get working package set. 

```

Library/PackageCache/com.unity.collections@0.0.9-preview.14/Unity.Collections/UnsafeUtilityEx.cs(41,34): error CS0117: 
'UnsafeUtility' does not contain a definition for 'IsUnmanaged'

```

**Comment by joeante** [comment]
The latest samples requires 19.1 beta
