### ISSUE TITLE
HelloCube4 subscene missing `Convert to Entity` monobehaviour

### ISSUE THREAD

**Issue by JerkyTreats** [Unity-Technologies/EntityComponentSystemSamples#115]
On `master` the subscene for HelloCube4 is missing the `Convert to Entity` script. Currently nothing happens when you run HelloCube4. 

Don't have write access so I can't submit PR. Simple enough fix.

**Comment by adamwestman** [comment]
I think you can fork and make a PR that way

**Comment by davidv-unity** [comment]
Hi, this will be fixed in the next release. You should see two stacked cubes spinning. For now you can press `Rebuild Entity Cache` on the `SubScene` script.
