### ISSUE TITLE
request EntityCommandBuffer.DestroyEntityHierarchy

### ISSUE THREAD

**Issue by adamwestman** [Unity-Technologies/EntityComponentSystemSamples#117]
Given the ConvertToEntity which enables parent/child hierarchies to be setup in a convenient manner. It seems useful to have a destruction command that destroys the whole hierarchy of children attached to an Entity. 

For example:
```c#
        [BurstCompile]
        struct RemoveDeadJob : IJobProcessComponentDataWithEntity<Health>
        {
            public bool playerDead;
            public EntityCommandBuffer commandBuffer;

            public void Execute(Entity entity, int index, ref Health health)
            {
                if (health.Value <= 0.0f || playerDead)
                {
                    commandBuffer.DestroyEntityHierarchy(entity);
                }
            }
        }
```
I can understand reluctance as Entities transforms and hierarchies are just one type of component. But without a convenience function like this, it seems like whomever is going to use a bunch of more complex prefab hierarchies will have a field day making sure everything is destroyed correctly.

**Comment by leethomason** [comment]
Internally tracking with issue 1160283. Closing this external issue.
