### ISSUE TITLE
CopyTransformFromGameObject component not updating Translation component

### ISSUE THREAD

**Issue by APWhiteside** [Unity-Technologies/EntityComponentSystemSamples#119]
Adding a CopyTransformFromGameObject will not subsequently update it's Translation component to the values that are in a gameObject Entity's transform component  

![image](https://user-images.githubusercontent.com/5629658/54439268-5f09f080-4730-11e9-8c0d-5e4acc4dd690.png)

This screen shot is from the entity debugger when the Transform was at a random non-zero location 

I see no mention of a change to CopyTransformFromGameObject in the recent release notes and such behaviour was previously present (at least before the Position component  was renamed to Translation but I can't say if that is part of the issue or not).

**Comment by APWhiteside** [comment]
CopyTransformToGameObject is working as expected

**Comment by macton** [comment]
CopyTransformFromGameObject copies to LocalToWorld. Replace Translation with LocalToWorld in this case.

**Comment by PaulUsul** [comment]
Thanks! Where is this behavior described?
