### ISSUE TITLE
Invalid link to Burst Compiler Documentation

### ISSUE THREAD

**Issue by JBean88** [Unity-Technologies/EntityComponentSystemSamples#120]
Burst Compiler Documentation link takes user to: https://docs.unity3d.com/Packages/com.unity.burst@0.0/manual/index.html  Where they receive this message:

"Error 404 - Page not found
This might be because:

You have typed the web address incorrectly, or the page you were looking for may have been moved, updated or deleted. Please search the Unity Manual and Unity Scripting API for the information you need."

Readme.md that contains the issue located at:
https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/Documentation~ 

Link to that page is on this unity forum post from a couple weeks ago: https://forum.unity.com/threads/api-deprecation-faq-0-0-23.636994/

**Comment by JBean88** [comment]
Possibly should go to: https://docs.unity3d.com/Packages/com.unity.burst@1.0/manual/index.html ?

**Comment by davidv-unity** [comment]
Hi & thanks for spotting that, it's fixed in our internal repositories and will land with the next release.
