### ISSUE TITLE
Get a Chunk With zero-sized IComponentData Throw Errors

### ISSUE THREAD

**Issue by Opeth001** [Unity-Technologies/EntityComponentSystemSamples#121]
Hello,
iterating over Entities with empty IComponentData is throwing  Errors , when i add any variable within my IComponentData i get no more errors .

Code Example:
  Entities.ForEach(( ref LocalPlayer localPlayer, ref  MouvementInput mouvementInput, ref AimInput aimInput) => {
                Debug.Log("InputSystem Has Changed : " + "Vertical : " + InputManager.instance.joysMouvement.Vertical + "  Horizontal: " + InputManager.instance.joysMouvement.Horizontal);
                mouvementInput = new MouvementInput { Value = new float2(InputManager.instance.joysMouvement.Horizontal, InputManager.instance.joysMouvement.Vertical) };
            }); 

Errors:
ArgumentException: ArchetypeChunk.GetNativeArray<LocalPlayer> cannot be called on zero-sized IComponentData
Unity.Entities.ArchetypeChunk.GetNativeArray[T] (Unity.Entities.ArchetypeChunkComponentType`1[T] chunkComponentType) (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/Iterators/ArchetypeChunkArray.cs:216)
Unity.Entities.EntityQueryBuilder.ForEach[T0,T1,T2] (Unity.Entities.EntityQueryBuilder+F_DDD`3[T0,T1,T2] action) (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/EntityQueryBuilder.gen.cs:625)
LocalPlayerInputs.OnUpdate () (at Assets/Scripts/ECS/LocalPlayer/Systems/LocalPlayerInputs.cs:18)
Unity.Entities.ComponentSystem.InternalUpdate () (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/ComponentSystem.cs:502)
Unity.Entities.ScriptBehaviourManager.Update () (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/ScriptBehaviourManager.cs:97)
Unity.Entities.ComponentSystemGroup.OnUpdate () (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/ComponentSystemGroup.cs:361)
UnityEngine.Debug:LogException(Exception)
Unity.Debug:LogException(Exception) (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/Stubs/Unity/Debug.cs:25)
Unity.Entities.ComponentSystemGroup:OnUpdate() (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/ComponentSystemGroup.cs:365)
Unity.Entities.ComponentSystem:InternalUpdate() (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/ComponentSystem.cs:502)
Unity.Entities.ScriptBehaviourManager:Update() (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/ScriptBehaviourManager.cs:97)
Unity.Entities.DummyDelegateWrapper:TriggerUpdate() (at Library/PackageCache/com.unity.entities@0.0.12-preview.29/Unity.Entities/ScriptBehaviourUpdateOrder.cs:129)

**Comment by davidv-unity** [comment]
Hi, this is by design as for zero-sized components there is literally no data to store (it's only part of the archetype) so you can not get a valid reference to it. You might want to look into `EntityArchetypeQuery` and chunk iteration as in this example [here](https://github.com/Unity-Technologies/dots/blob/master/Documentation~/chunk_iteration.md). If you have any questions about this feel free to reopen the issue or visit the forums. Kind Regards!

**Comment by Opeth001** [comment]
Hi devidv-unity,
Thank you for the Reply ! ^_^
the link you posted is dead :( .

**Comment by davidv-unity** [comment]
Sorry for that, fixed it (posted the link to the internal docs not the published one). `EntityArchetypeQuery` might just be what you want and unless `ForEach` (right now) you can utilize multiple threads which can improve performance! Let me know if you got any issues!
