### ISSUE TITLE
EntityTypeR0 invalid in TransformSystem

### ISSUE THREAD

**Issue by AnibersStudio** [Unity-Technologies/EntityComponentSystemSamples#122]
TransformSystem.cs:320 in UpdateFrozen()
`var chunkEntities = chunk.GetNativeArray(EntityTypeRO);`
chunkEntities may be invalid ("deallocated" in the log) cause EntityTypeR0 is invalid.
If I add
`EntityTypeRO = GetArchetypeChunkEntityType();`
before this line and everything will be OK.
The most recent updating happens in GatherTypes(), line 1173. Adding one GatherTypes() before UpdateFrozen() also solve the problem.
Cound it be possible that GatherFrozenChunks() or UpdatePendingFrozen() has invalidated EntityTypeR0 ?

**Comment by leethomason** [comment]
If this is still happening in the new version, could you submit a bug through Unity with current steps? Thanks very much.
