### ISSUE TITLE
unity.physics error when build android with il2cpp

### ISSUE THREAD

**Issue by ggdagcheng** [Unity-Technologies/EntityComponentSystemSamples#123]
Failed running D:\Unity\Hub\Editor\2019.1.0b8\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARMv7" --configuration="Release" --outputpath="G:\Gameproject\EntityComponentSystemSamples\UnityPhysicsExamples\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a\libil2cpp.so" --cachedirectory="G:\Gameproject\EntityComponentSystemSamples\UnityPhysicsExamples\Assets\..\Library\il2cpp_android_armeabi-v7a/il2cpp_cache" --additional-include-directories="D:\Unity\Hub\Editor\2019.1.0b8\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="D:\Unity\Hub\Editor\2019.1.0b8\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="D:/Unity/Hub/Editor/2019.1.0b8/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" --profiler-report --map-file-parser=D:/Unity/Hub/Editor/2019.1.0b8/Editor/Data/Tools/MapFileParser/MapFileParser.exe --directory=G:/Gameproject/EntityComponentSystemSamples/UnityPhysicsExamples/Temp/StagingArea/assets/bin/Data/Managed --generatedcppdir=G:/Gameproject/EntityComponentSystemSamples/UnityPhysicsExamples/Temp/StagingArea/Il2Cpp/il2cppOutput --extra-types-file=G:/Gameproject/EntityComponentSystemSamples/UnityPhysicsExamples/Temp/StagingArea/Il2Cpp/extra-types.txt 

stdout:

Building libil2cpp.so with AndroidToolChain

	Output directory: G:\Gameproject\EntityComponentSystemSamples\UnityPhysicsExamples\Temp\StagingArea\assets\bin\Data\Native\armeabi-v7a

	Cache directory: G:\Gameproject\EntityComponentSystemSamples\UnityPhysicsExamples\Library\il2cpp_android_armeabi-v7a\il2cpp_cache

il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: G:\Gameproject\EntityComponentSystemSamples\UnityPhysicsExamples\Temp\StagingArea\Il2Cpp\il2cppOutput\Il2CppAttributes.cpp:82129:91: error: no member named 'numeric_limits' in namespace 'std'

                SoftRangeAttribute_set_TextFieldMax_mDEC5E6B1B9BB8113480772A81F7ABBDB9A5B00A4(tmp, std::numeric_limits<float>::max(), NULL);

                                                                                                   ~~~~~^

G:\Gameproject\EntityComponentSystemSamples\UnityPhysicsExamples\Temp\StagingArea\Il2Cpp\il2cppOutput\Il2CppAttributes.cpp:82129:111: error: expected '(' for function-style cast or type construction

                SoftRangeAttribute_set_TextFieldMax_mDEC5E6B1B9BB8113480772A81F7ABBDB9A5B00A4(tmp, std::numeric_limits<float>::max(), NULL);

                                                                                                                       ~~~~~^

G:\Gameproject\EntityComponentSystemSamples\UnityPhysicsExamples\Temp\StagingArea\Il2Cpp\il2cppOutput\Il2CppAttributes.cpp:82129:114: error: no member named 'max' in the global namespace

                SoftRangeAttribute_set_TextFieldMax_mDEC5E6B1B9BB8113480772A81F7ABBDB9A5B00A4(tmp, std::numeric_limits<float>::max(), NULL);

                                                                                                                             ~~^

3 errors generated.

**Comment by ggdagcheng** [comment]
@HenrikPoulsen

**Comment by Edgar-BlipparDev** [comment]
Point is I have to build with il2ccp... Experiencing same issues across board on windows

**Comment by leethomason** [comment]
This is being investigated internally (1160276). Closing the external issue.
