### ISSUE TITLE
EntityArchetypeQuery  how to Access Any specified Components

### ISSUE THREAD

**Issue by Opeth001** [Unity-Technologies/EntityComponentSystemSamples#124]
i have  question about EntityArchetypeQuery :
how  to check if an entity contains a the specified Component within the matched  ANY filter ?

**Comment by jo3w4rd** [comment]
In IJobChunk, you get an ArchetypeChunk object that contains the Has<T> function for that.

https://docs.unity3d.com/Packages/com.unity.entities@0.0/api/Unity.Entities.ArchetypeChunk.html#Unity_Entities_ArchetypeChunk_Has__1_Unity_Entities_ArchetypeChunkComponentType___0__

**Comment by Opeth001** [comment]
Thank you for your Help !!! 
but i forgot to specify the IJobProcessComponentData :p

**Comment by jo3w4rd** [comment]
Sorry, you can't use IJobProcessComponentData for that. But if you are using a custom query, you are halfway to IJobChunk anyway. It is also more efficient to do in IJobChunk since you only need to check once per chunk rather than for every entity.
