### ISSUE TITLE
Please make an example showing how to control camera in ECS.

### ISSUE THREAD

**Issue by jackalcooper** [Unity-Technologies/EntityComponentSystemSamples#127]
Failed to find the best practice to implement a player follower camera in latest ECS fashion.

**Comment by Gotcab** [comment]
Are you looking for pure or hybrid implementation?

**Comment by jackalcooper** [comment]
Pure probably? I’m using a system to save the transform of main camera when it is started, which I think is kind of clumsy.

**Comment by Opeth001** [comment]
Im using a CameraFollowSystem, it Follows my Local Player working in a Pure Way.

I hope it will help you!



using System.Collections;
using System.Collections.Generic;
using Unity.Burst;
using Unity.Collections;
using Unity.Entities;
using Unity.Jobs;
using Unity.Mathematics;
using Unity.Transforms;
using UnityEngine;


[UpdateAfter(typeof(PlayersMovementSystem))]
public class CameraFollowSystem : JobComponentSystem
{ 
    private EntityQuery m_LocalPlayer; 

    protected override void OnCreateManager()
    {
        // Cached access to a set of ComponentData based on a specific query 
        m_LocalPlayer = GetEntityQuery(  ComponentType.ReadOnly<Translation>() , ComponentType.ReadOnly<LocalPlayer>()); 
    }

    [BurstCompile]
    public struct CameraFollowJob : IJobForEach<Translation, Rotation, CameraComponent>
    {
        [DeallocateOnJobCompletion]
        public NativeArray<Translation> target; 

      
        public float deltaTime;   
        public void Execute(ref Translation camPosition, ref Rotation camRotation, [ReadOnly]  ref CameraComponent c2)
        {
            // check if player exist
            if (target.Length == 0)
                return;

            // Follow the Player
            float3 desiredPosition = target[0].Value + GameBootstrap.instance.offset;
            float3 smoothedPosition = math.lerp(camPosition.Value, desiredPosition, GameBootstrap.instance.CameraSmoothSpeed * deltaTime);
            camPosition.Value = smoothedPosition;

            // Rotate Camera to the Player
            float3 lookVector = target[0].Value - camPosition.Value;
            Quaternion rotation = Quaternion.LookRotation(lookVector);
            camRotation.Value = rotation;
        }
    } 

    protected override JobHandle OnUpdate(JobHandle inputDeps)
    { 
        var job = new CameraFollowJob
        {
            target = m_LocalPlayer.ToComponentDataArray<Translation>(Allocator.TempJob),
            deltaTime = Time.deltaTime
        };
        return job.Schedule(this, inputDeps);
         
    }
}

**Comment by jackalcooper** [comment]
I will give it a try. Thanks a lot @Opeth001 !

**Comment by Opeth001** [comment]
Your Welcome!

**Comment by DragonMastery** [comment]
@Opeth001 I thought _translation_ and _rotation_ were depreciated?

**Comment by Opeth001** [comment]
@DragonMastery  they are taged as depricated, but still be used even by them within the new Unity Physics ( any Physics Body need them to Works correctly ). so that means  if they totally depricate it they have to provide a new Component with the same fontionality.
but u can use the TransformAccess for this case if you dont wont to use Depricated Proxies.

**Comment by DragonMastery** [comment]
@Opeth001 Ok that makes sense, I am fine with using them. I am trying to implement your camera follow script into a Pure ECS Version I am trying to build [Here](https://github.com/DragonMastery/SurvivalShooterPureECS/tree/master/SurvivalShooterECS/Assets/ECS/PureScripts). I cannot see to get the camera to move or the player. Can you help me out? I can see in the entity that the translation is moving for both but they are not moving in game.

**Comment by Opeth001** [comment]
@DragonMastery 
use the Convert To Entity Component with Conversion mode as Convert and Inject GameObject

**Comment by DragonMastery** [comment]
@Opeth001 Yea, I am having troubles getting it all to work together;

**Comment by Opeth001** [comment]
This is how my Camera Entity looks like.
![map1](https://user-images.githubusercontent.com/32723106/56058851-e2842500-5d62-11e9-8c26-c78d5f3ee7ad.JPG)

**Comment by WAYNGROUP** [comment]
Hello, I used a cinemachine camera "as usual" except the target is an empty under the game object I want to follow that looks like that :

![image](https://user-images.githubusercontent.com/47318939/57323009-333e3200-7105-11e9-9d92-48ba67f1946e.png)

so the cinemachine virtual camera looks like : 
![image](https://user-images.githubusercontent.com/47318939/57323049-4b15b600-7105-11e9-9ffa-8986547700d0.png)

And Main camera like : 
![image](https://user-images.githubusercontent.com/47318939/57323106-6ed8fc00-7105-11e9-9c52-129e37590a07.png)

**Comment by leethomason** [comment]
Closing this issue pending additional feedback. It's a hard to tell if there is still an actionable bug / issue.

**Comment by qaisbayabani** [comment]
https://www.youtube.com/watch?v=yIPOCqMYTTg

**Comment by qaisbayabani** [comment]
https://www.youtube.com/watch?v=yIPOCqMYTTg
