### ISSUE TITLE
can't open the project by  2019.2 beta

### ISSUE THREAD

**Issue by zelinDavid** [Unity-Technologies/EntityComponentSystemSamples#128]
![image](https://user-images.githubusercontent.com/16894134/55286518-3ee45d80-53cf-11e9-9053-ec7659aeb23c.png)

I'm sorry but I tried many times to open the project by the beta version of unity, and always went wrong. you can have a try.

**Comment by zelinDavid** [comment]
and finally I opened it by using 2019.1.0 , but it really waste  some of my time..

**Comment by MostHated** [comment]
2019.2 is an Alpha, not a Beta, so it is much more likely that you are going to run into issues. That is why the Alphas and Beta's exist, for users to report bugs and issues that are found so that they can be fixed and the versions can become bug free and stable. Are you not going to post any error messages or details as to what happened when you tried to open it in 2019.2? Simply saying "I tried many times and it doesn't work" definitely is a waste of time.

**Comment by zelinDavid** [comment]
you can try it by yourself, and  when openning the project by unity editor 2019.2 , it will break down directly.

**Comment by MostHated** [comment]
Why would I go and install it and go through all that to get the info that they would like for you to provide when you could have just done it in the first place when you took the time to come here, make a post that just said "it doesn't work" only, already?

Do you realize that actually making this post was just as much of a waste of time as what you actually posted about? What good does saying "I tried it, it doesn't work" do? They have no idea any details *at all*. They have no idea what version of 2019.2 you were using, there are at least 8-9 of them. They don't know if you were using Windows and if you were, was it 7, 8, 10? What build number of that version, or was it not even Windows and it was it Mac, or Linux? 

How do you expect anyone to fix anything when no one has any idea what you are talking about? It's like going to the Dr and when they asked you what was wrong you just said "it doesn't work".  It does no one any good in trying to fix it if no one knows anything about it.

**Comment by zelinDavid** [comment]
I'm sorry but I'm new to add issue in git. so if I annoyed you , I say I'm sorry. I didn't record the error.   I used window10, unity 2019.2.0a9.  and I install the unity Editor by unity hub.   I'm in commpany now.maybe I cound show you a video after  going off work.

**Comment by zelinDavid** [comment]
I just donwload the project. unzip it. and open the samples by the unity Editor. then after showing import asset. it breaks down. more detail. I will show you a video

**Comment by Will9371** [comment]
Having similar problems, here is some more detail.  Using Unity version 2019.2.0a14.  Created empty project, installed Entities and Hybrid Renderer through the Package Manager, changed Api Compatibility Level to .NET 4.x, and unzipped example repository into Assets folder of project.  I have 153 compile errors listed in the console, all of them are in UnityPhysicsExamples\Assets subfolder.  The text of the first error listed is as follows:

Assets\EntityComponentSystemSamples-master\UnityPhysicsExamples\Assets\Common\Scripts\BasePhysicsDemo.cs(9,32): error CS0234: The type or namespace name 'Collider' does not exist in the namespace 'Unity.Physics' (are you missing an assembly reference?)

Another example, also from the library section of a script:
Assets\EntityComponentSystemSamples-master\UnityPhysicsExamples\Assets\Demos\6. Use Cases\PlanetGravity\Scripts\PlanetGravityBehaviour.cs(3,21): error CS0234: The type or namespace name 'Systems' does not exist in the namespace 'Unity.Physics' (are you missing an assembly reference?)

The remaining errors are similar, involving types not being recognized: 
Assets\EntityComponentSystemSamples-master\UnityPhysicsExamples\Assets\Demos\6. Use Cases\CharacterController\Scripts\CharacterControllerComponent.cs(262,16): error CS0246: The type or namespace name 'BlockStream' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Will9371** [comment]
Problem is in the Physics system.  Delete the UnityPhysicsExamples subfolder and all of the errors should go away...not an ideal solution, of course, because then you don't have the Physics examples.

With the Physics folder present, some of the errors can be resolved simply by deleting some of the library references (e.g. Unity.Physics.Systems), so it is clearly an issue of the repo not being updated to reflect changes to 2019.2.

**Comment by Will9371** [comment]
Turns out to be an easy fix--you just need to import Unity Physics in the Package Manager.

**Comment by leethomason** [comment]
This bug is being internally tracked (1160280) which will close the external issue. Thanks for reporting.
