### ISSUE TITLE
Build on iOS broken?

### ISSUE THREAD

**Issue by flashno** [Unity-Technologies/EntityComponentSystemSamples#135]
Building EntityComponentSystemSamples on iOS leads to EXC_BAD_ACCESS 

1. Having version 0.0.12 of Entities, and version 0.0.1 of Hybrid Renderer on Unity 2019.1.0b9.
I built the HelloCube_05_SpawnFromMonoBehaviour scene on my iphone XS and it crashes everytime. First there was a codestripping issue, but I got rid of that by using a Preserve attibute (case 1070862). Now I get issues with what seems like Burst.cpp. 

2. Build the project on iOS and run on xcode version 10.1.

**Comment by leethomason** [comment]
If this bug persists in the current version, please file a bug report via Help -> Report a Bug. Many thanks!
