### ISSUE TITLE
Entities.ForEach should just be ForEach

### ISSUE THREAD

**Issue by stormmuller** [Unity-Technologies/EntityComponentSystemSamples#137]
I'm going through the very [first sample](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/Samples/Assets/HelloECS/HelloCube_01_ForEach) and when writing the [system ](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Samples/Assets/HelloECS/HelloCube_01_ForEach/RotationSpeedSystem.cs) `Entities` is not defined. We already reference the namespace `Unity.Entities` and changing the code to be just `ForEach` as opposed to `Entities.ForEach` works.

I'm using Unity 2019.1.0f2

**Comment by jo3w4rd** [comment]
Can you verify which version of Unity.Entities you are using? We changed the way you write the ForEach loops as of version 0.0.24. The correct way is to use Entities.ForEach now.

**Comment by stormmuller** [comment]
Changed my version of Unity.Entities form 0.0.12 preview.24 to 0.0.12 preview.30 and it's dandy. Thanks @jo3w4rd
