### ISSUE TITLE
Example-08 HelloCube Only 1-2 fps after a while

### ISSUE THREAD

**Issue by stormouse** [Unity-Technologies/EntityComponentSystemSamples#141]
If you run example 08 HelloCube, which constantly spawn and destory cube entities, at first the fps on my machine is about 200. After a while (after they all turn green) the fps drops to less than 10. Any explanation to the performance loss?

**Comment by sunfffd** [comment]
Same here, 
On my machine, the number of verts starts from 2.5M and drops to around 550k and goes back up again, while the fps is dropping to around 30 fps

**Comment by leethomason** [comment]
Thanks for the bug report and confirmation. Submitting internally (2258), which will close this externally.
