### ISSUE TITLE
SetSingleton fails on IConvertGameObjectToEntity

### ISSUE THREAD

**Issue by aeldron** [Unity-Technologies/EntityComponentSystemSamples#142]
SetSingleton throws an error on GameObjects with IConvertGameObjectToEntity.   Here's an example:

```
[RequiresEntityConversion]
public class DefaultSettingsProxy : MonoBehaviour, IConvertGameObjectToEntity
{
    public void Convert(Entity entity, EntityManager dstManager, GameObjectConversionSystem conversionSystem)
    {
        var e = dstManager.CreateEntity(typeof(EcsTestData));
        conversionSystem.SetSingleton<EcsTestData>(new EcsTestData(10)));
     }
}
```

This throws an exception:

> InvalidOperationException: SetSingleton<EcsTestData >() requires that exactly one EcsTestData exists but there are 0.

**Expected result:**  _SetSingleton_ should work on _IConvertGameObjectToEntity.Convert_ just as it does on _ComponentSystem.OnCreate_

**Comment by joeante** [comment]
This is by design. The conversionSystem is on a different world than dstManger
conversionSystem.EntityManager is a world containing the game objects of the converted data itself...
