### ISSUE TITLE
ComponentSystemBase.HasSingleton returns true for any component archetype for which one entity exists 

### ISSUE THREAD

**Issue by jo3w4rd** [Unity-Technologies/EntityComponentSystemSamples#143]
The following function  only checks whether one entity of an archetype exists. A Singleton is expressly a type for which only one can ever exist. This function implementation returns true for any single-component archetype that happens to match only one entity at the time it is called. 

It also doesn't check whether the component type exists in more than one archetype, which is a requirement to be a singleton.

```
public bool HasSingleton<T>()
            where T : struct, IComponentData
        {
            var type = ComponentType.ReadOnly<T>();
            var query = GetEntityQueryInternal(&type, 1);
            return !query.IsEmptyIgnoreFilter;
        }
```

It seems like this could lead to possibly subtle, hard to find bugs in game code.

Possibly we should move the code to EntityQuery.IsSingleton so that all the Singleton code is defined in one place.

**Comment by leethomason** [comment]
Submitted internally (2256). Closing external issue.
