### ISSUE TITLE
Unity.Physics.Systems.StepPhysicsWorld is frame-rate dependent.

### ISSUE THREAD

**Issue by Razzeeyy** [Unity-Technologies/EntityComponentSystemSamples#145]
Currently unity physics is frame-rate dependent due to it using Time.fixedDeltaTime to schedule simulation jobs but not making sure to throttle the scheduling itself. Resulting in job being called as fast as possible but with always constant fixedDeltaTime.

File Unity.Physics->ECS->Systems->StepPhysicsWorld::OnUpdate(JobHandle inputDeps)
Line 100: `TimeStep = UnityEngine.Time.fixedDeltaTime,`

A quick fix would be to just use `UnityEngine.Time.deltaTime` there.
That would make physics frame-rate independent althought potentially unstable on lower frame-rates, but I think that's still better than having frame-rate dependent physics and takes less time to fix than implementing proper time throttling logic.

**Comment by leethomason** [comment]
Being processed internally (2255); closing the external issue.
