### ISSUE TITLE
unity physics crash on android with il2cpp

### ISSUE THREAD

**Issue by kumbayaco** [Unity-Technologies/EntityComponentSystemSamples#148]
it crashes in 'Collide parada' scene when colliders hit the ground.  but no crash happend with one built with mono.

crash log
![image](https://user-images.githubusercontent.com/2878666/60169407-38804900-9839-11e9-9922-59eb26daef2c.png)

cpp:
![image](https://user-images.githubusercontent.com/2878666/60169436-403fed80-9839-11e9-922d-ed476209d840.png)

**Comment by davidv-unity** [comment]
Hi @kumbayaco, thank you for pointing that out. We could reproduce it but did not see any further crashes with later releases, so I'll close this issue now, please let me know if you still had any issues!
