### ISSUE TITLE
Cannot open samples project via Unity Hub - required version unavailable for download

### ISSUE THREAD

**Issue by Manningham** [Unity-Technologies/EntityComponentSystemSamples#149]
The Samples project in this repo requires Unity version 2019.1.0f1, but the closest available version is 2019.1.0f2.  Unity hub disallows opening the project.

Also tried opening the 2019.1.0f2 install directly from .exe, hoping to open the Samples project from within the running editor, but running the executable just launches Unity Hub again.

**Comment by Manningham** [comment]
https://unity3d.com/get-unity/download/archive

**Comment by barantaran** [comment]
Just normally opened and launched all scenes with 2019.1.8f1 ("Select a version" in Unity Hub then "Confirm" in dialog window). Do I missed smth?

**Comment by Manningham** [comment]
Hm, am I using UnityHub wrong? Don't see any other buttons to click - linked the blocking warning I'm seeing below.

![Unity_Version_Warning](https://user-images.githubusercontent.com/12063122/60401783-3a991f00-9b3b-11e9-89b2-b98714f0a9e8.png)
![Unity_Installs](https://user-images.githubusercontent.com/12063122/60401784-3a991f00-9b3b-11e9-8f14-54eeeacc11b1.png)

**Comment by barantaran** [comment]
Try to use "Select a version" drop-down list just to the right of "Samples" to change the version.

**Comment by Manningham** [comment]
Oh nice I didn't see that light gray arrow!  Works when I switch to 2019.1.0f2, thanks!

I guess I assumed that, since Unity could figure out the project's needed version, it could also figure out which of my installs to use to open it.
