### ISSUE TITLE
How to destroy PhysicsJoint entity?

### ISSUE THREAD

**Issue by phields** [Unity-Technologies/EntityComponentSystemSamples#151]
I have tried to let spawn and remove system work with PhysicsJoint together, but got errors...

**Comment by phields** [comment]
![image](https://user-images.githubusercontent.com/31947421/60759379-110a5700-a057-11e9-927d-4dedbe306e22.png)
Is there any safe way to remove the PhysicsJoint entity?

**Comment by amechtley** [comment]
Hi! All you should need to do is remove the `PhysicsJoint` component (which should be on some other `Entity` than one of those constrained by the joint). This basic example can be used in e.g., the physics joint sample scenes and removes all joints:

```
using Unity.Entities;
using Unity.Physics;
using UnityEngine;

public class NewBehaviourScript : ComponentSystem
{
    protected override void OnUpdate()
    {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            Entities.ForEach((Entity e, ref PhysicsJoint joint) =>
            {
                PostUpdateCommands.RemoveComponent<PhysicsJoint>(e);
            });
        }
    }
}
```
