### ISSUE TITLE
Compile error after fresh import in 2019.2.0b6

### ISSUE THREAD

**Issue by floAr** [Unity-Technologies/EntityComponentSystemSamples#152]
After creating a new project from hdrp template importing entities package results in: `Library\PackageCache\com.unity.burst@1.0.4\Editor\BurstAotCompiler.cs(638,32): error CS7036: There is no argument given that corresponds to the required formal parameter 'exceptionType' of 'BuildReport.AddMessage(LogType, string, string)'`

**Comment by floAr** [comment]
Seems to be fixed by upgrading Burst package from 1.0.4 to current (1.1.1)

**Comment by davidv-unity** [comment]
Thank you @floAr for pointing it out and providing providing the workaround! 
Closing this as it has been fixed with later releases.
