### ISSUE TITLE
Physics ecs

### ISSUE THREAD

**Issue by KazumiOmidarea** [Unity-Technologies/EntityComponentSystemSamples#155]
I'm trying to get the physics examples to work , I've downloaded through the package manager the hybrid renderer ,entities with their dependencies and the unity physics as well as the input system.
I've marked on the player settings to allow unsafe code and set the input handling to the input system(preview)
But even after all of this I've got some errors in the InputActions file so I've changed all the GetActionMap/GetAction to FindActionMap/FindAction and that solved the problem on this script however after fixing that the importing seemed to continue and another InputActions file was created which caused a bunch of error on a few system(CameraFollowActiveVehicleSystem,ChangeActiveVehicleSystem,DemoInputGatheringSystem)

is there a read me on how to get this thing to work?
also the main shader for everything seems to be missing (Didn't have the HDRP or the LWRP on this project)

**Comment by amechtley** [comment]
Hi! You should just be able to open the project folder directly in this repo (i.e. `UnityPhysicsSamples` is a complete Unity project). No need to pull in anything from package manager.
