### ISSUE TITLE
boidexample Won't run if build into standalone il2cpp Master

### ISSUE THREAD

**Issue by poshih** [Unity-Technologies/EntityComponentSystemSamples#156]
use boidexample as scene 0, build master build, game frozen with high cpu usage, no visual, not responding

runs fine if it's il2cpp release build.

call stack of the dump

 	ntdll.dll!NtReleaseSemaphore()	Unknown
 	KERNELBASE.dll!ReleaseSemaphore()	Unknown
 	UnityPlayer.dll!CappedSemaphore::Signal(int)	Unknown
 	UnityPlayer.dll!JobBatchDispatcher::~JobBatchDispatcher(void)	Unknown
 	UnityPlayer.dll!JobHandle_CUSTOM_ScheduleBatchedJobsAndComplete(struct JobFence &)	Unknown
 	[Inline Frame] GameAssembly.dll!JobHandle_ScheduleBatchedJobsAndComplete_mF69F070E0ADFDD88FE72B57143BF6BF29B27F80D(JobHandle_tDA498A2E49AEDE014468F416A8A98A6B258D73D1 *) Line 15396	C++
 	[Inline Frame] GameAssembly.dll!JobHandle_Complete_m5EFD637001D6A9E0528E60C294FCA5354FD1E797(JobHandle_tDA498A2E49AEDE014468F416A8A98A6B258D73D1 *) Line 15367	C++
 	GameAssembly.dll!EntityManager_AddComponent_m7D2A036C596FD40842206A709019AE9CF4C70150(EntityManager_tD03BBAE8A03BE6E803E142278B44DADB1F999C14 * __this, UnsafeMatchingArchetypePtrList_t35177C957F260B440EBFE45DD90F42639DDFAA18 ___archetypeList0, EntityQueryFilter_t8094C471CFB0EB9B8AEAA945A46E183CEDEC79AB ___filter1, ComponentType_tC4D03CEDBA5BCBA47001797965E7CF939CFBDAF1 ___componentType2, const MethodInfo * method) Line 15781	C++
 	GameAssembly.dll!EntityManager_AddComponent_m75599D8A5FFF4D7C41616F915EB68B8710C229FB(EntityManager_tD03BBAE8A03BE6E803E142278B44DADB1F999C14 * __this, EntityQuery_t76BED15925C813EF17FA4A29A4D9262AB62AD76A * ___entityQuery0, ComponentType_tC4D03CEDBA5BCBA47001797965E7CF939CFBDAF1 ___componentType1, const MethodInfo * method) Line 15348	C++
 	[Inline Frame] GameAssembly.dll!EntityManager_AddComponent_TisDeclaredReferenceObjectsTag_tF14F574CD666A3022D4E02555AF6DEF93BF40911_mE5C3305D03F03A292FB3DD98DF6B8CCC1E9CB24B_gshared(EntityManager_tD03BBAE8A03BE6E803E142278B44DADB1F999C14 *) Line 25932	C++
 	[Inline Frame] GameAssembly.dll!EntityManager_AddComponent_TisDeclaredReferenceObjectsTag_tF14F574CD666A3022D4E02555AF6DEF93BF40911_mE5C3305D03F03A292FB3DD98DF6B8CCC1E9CB24B(EntityManager_tD03BBAE8A03BE6E803E142278B44DADB1F999C14 *) Line 11281	C++
 	GameAssembly.dll!GameObjectConversionUtility_DeclareReferencedObjects_m86BDCC1A908C7016335A33B423FA49299338B354(World_tEEA075348FAEC96EE224554FCDED78254768804E * ___gameObjectWorld0, GameObjectConversionMappingSystem_t6A9AECD0692DEAB55D3D7628E85BE03B1BBA1812 * ___mappingSystem1, const MethodInfo * method) Line 19682	C++
 	GameAssembly.dll!GameObjectConversionUtility_Convert_m02676BCB0DB177EF55173F8CCF1C69263863F7F1(World_tEEA075348FAEC96EE224554FCDED78254768804E * ___gameObjectWorld0, const MethodInfo * method) Line 19810	C++
>	GameAssembly.dll!ConvertToEntity_ConvertHierarchy_mB53322FB042977C5F126434561BBA8EE4EE28373(GameObject_tBD1244AD56B4E59AAD76E5E7C9282EC5CE434F0F * ___root0, const MethodInfo * method) Line 17190	C++
 	GameAssembly.dll!RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017(void(*)() methodPointer, const MethodInfo * methodMetadata, void * obj, void * * args) Line 41897	C++

**Comment by Drealmer** [comment]
Can't repro, old issue, closing.
