### ISSUE TITLE
Wrong max variable in count for loop

### ISSUE THREAD

**Issue by profjdbayliss** [Unity-Technologies/EntityComponentSystemSamples#157]
In  	Spawner_ForEachWithEntityChanges.cs the following code:

for (int x = 0; x < CountX; x++)
            {
                for (int y = 0; y < CountX; y++)
                {

The second for loop should go to CountY rather than CountX. I changed values and it was wrong because of the y loop error.

**Comment by Drealmer** [comment]
We fixed that a while ago and apparently forgot to close the issue. Thanks for reporting!
