### ISSUE TITLE
Errors with multipple collisions at the same time (2d1 Sample)

### ISSUE THREAD

**Issue by krol1k** [Unity-Technologies/EntityComponentSystemSamples#158]
2d1 Example with material changing

When several triggers overlap one collider at the same time, then this error comes out:
"ArgumentException: The component of type:OverlappingTriggerVolume has already been added to the entity."

When several trigger overlaps several colliders at the same time, then this error comes out:
"InvalidOperationException: The NativeArray has been deallocated, it is not allowed to access it"

**Comment by amechtley** [comment]
Thanks! As far as I can tell, this is fixed in the new version of entities, which should be available soon. Please re-open this issue if you are still seeing this problem after we have updated both entities and Unity Physics.
