### ISSUE TITLE
TODO item done - should be removed

### ISSUE THREAD

**Issue by Sibz** [Unity-Technologies/EntityComponentSystemSamples#160]
Looks like this has been jobified, but is still calling `inDeps.Complete();`

https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/d616c1b077c306e6f31b41a3970799e4b132139b/UnityPhysicsSamples/Assets/Demos/5.%20Modify/Scripts/ModifyNarrowphaseContactsBehaviour.cs#L75-L81

**Comment by amechtley** [comment]
Thanks! Will be done in the next release
