### ISSUE TITLE
Cannot effectively debug memory leaks in ecs

### ISSUE THREAD

**Issue by astropuffin** [Unity-Technologies/EntityComponentSystemSamples#161]
error:
```
Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak
To Debug, enable the define: TLA_DEBUG_STACK_LEAK in ThreadsafeLinearAllocator.cpp. This will output the callstacks of the leaked allocations
```

There have been numerous reports of this issue over the past two years, but no answers on how to actually either
1. Enable this flag to report what allocation is suspected of having a leak.
2. Some other workaround to find the actual cause of leaks.

Suggestions have ranged from "restart unity" to "it's harmless". Restarting occasionally fixes some leaks, but that's not going to help me debug in general. Specific code is not what this issue is about, but in my case my game is working fine, but my unit tests were flaky because _one_ of my unit tests had a leak and it caused a random unit test later on to fail. It was a one line fix that took forever to find. It would have been five minutes if Unity had allowed me to enable debugging on _which_ allocation is having an issue.

Happy to open an issue somewhere else if this is not the correct forum.

**Comment by Drealmer** [comment]
We now have proper callstacks for those leaks, see the Jobs menu, Leak Detection, Full Stack Traces.
