### ISSUE TITLE
Atoms ? JointData.Create( ? )

### ISSUE THREAD

**Issue by nukadelic** [Unity-Technologies/EntityComponentSystemSamples#162]
Hi, I'm trying to create a custom ecs physics joint

I see the following metadata in the Unity.Physics.dll : `JointData.Create( Math.MTransform aFromJoint, Math.MTransform bFromJoint, Constraint[] constraints )` 

Which is being used in `LimitDOFJoint` and in there there is this line in the comments:
> `...This is achieved by combining the appropriate lower level 'constraint atoms' to form the higher level Joint.`

What do the atoms mean ? where can i read more the constraints * input argument ? Is there an easier way creating custom joints instead ?

**Comment by carpetbagger** [comment]
`Joints `are made up of a number of `Constraints`. `Constraints `are atomic in that they are not broken down into smaller pieces (hence constraint atoms - its a throw over name from the Havok Physics C++ SDK) 

The latest release has a cleaner interface for dealing with the `Joints`.

**Comment by nukadelic** [comment]
Thanks for the replay, do you have discord ? I'd like to chat - add me `Wad1m#6844`
