### ISSUE TITLE
Entity Debugger documentation misses info on how to open it

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/EntityComponentSystemSamples#163]
Hi! The [Entity Debugger info page](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/ECSSamples/Documentation/entity_debugger_overview.md) should perhaps include information on how to access it? I.e. Windows -> Analysis -> Entity Debugger. Thanks!

**Comment by jo3w4rd** [comment]
Added this information to the source document (which doesn't live in this repo), so the version here will get updated the next time we refresh this samples repository.
