### ISSUE TITLE
Different case conventions for functions?

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/EntityComponentSystemSamples#165]
Hi! This is more of an understanding issue (and maybe it's a question for the math library). In the code I see some functions starting with upper-case, like quaternion.AxisAngle(), and others with a lowercase, like math.normalize(). Why the difference? Thanks!

```
var jobHandle = Entities
    .WithName("RotationSpeedSystem_ForEach")
    .ForEach((ref Rotation rotation, in RotationSpeed_ForEach rotationSpeed) =>
        {
            rotation.Value = math.mul
            (
                math.normalize(rotation.Value),
                quaternion.AxisAngle(
                math.up(),
                rotationSpeed.RadiansPerSecond * deltaTime
            )
        );
        })
    .Schedule(inputDependencies);
```

There's also e.g. all lower-case instead of camel-case, like "math.normalizesafe", which somewhat lowers readability.

**Comment by davidv-unity** [comment]
Hi @JPhilipp, [Unity.Mathematics](https://github.com/Unity-Technologies/Unity.Mathematics) uses lowercase names: the burst compiler knows how to generate efficient SIMD code for that.  The uppercase math helpers are part of (classic) UnityEngine. 

Rule of thumb: if you are using DOTS/burst in your project, go for the (lowercase) Unity.Mathematics, if you are using classic Unity (GameObjects and MonoBehaviours) use the uppercase ones.
