### ISSUE TITLE
Error compiling fresh import

### ISSUE THREAD

**Issue by LetsCode-Angus** [Unity-Technologies/EntityComponentSystemSamples#166]
After importing Entities (v1.1.1) into unity through the package manager, the console was being repeatedly logged with the following errors:

`Library\PackageCache\com.unity.burst@1.1.2\Runtime\BurstCompiler.cs(50,83): error CS0117: 'BurstCompilerService' does not contain a definition for 'GetCurrentExecutionMode'`

`Library\PackageCache\com.unity.burst@1.1.2\Runtime\BurstCompiler.cs(42,49): error CS0117: 'BurstCompilerService' does not contain a definition for 'SetCurrentExecutionMode'`

**Comment by btwist** [comment]
I currently also have this problem. did you find a solution?

**Comment by Drealmer** [comment]
Likely not relevant anymore, this doesn't seem to happen with current versions, closing.
