### ISSUE TITLE
Subscene is not loaded

### ISSUE THREAD

**Issue by narendraprasaths** [Unity-Technologies/EntityComponentSystemSamples#170]
After the standalone build, the subscene is not loading while runs in the windows system. But it works fine in the editor. Why, what is the problem?

**Comment by liucailin** [comment]
same issue not work at android play

**Comment by dingxiaowei** [comment]
SubScene maks Editor Stuck

**Comment by VeyronSakai** [comment]
The same is happening on iOS devices (iOS version is 13.3).

**Comment by Drealmer** [comment]
Standalone builds have to be made using "build configurations". You'll find some useful information in this forum thread:
https://forum.unity.com/threads/building-dots-projects-doesnt-work.867247/
Thanks for reporting the issue, I've added an internal note for us to provide some documentation about this.

**Comment by nioan** [comment]
Are Subscenese supposed to work with IL2CPP as the scripting backend?

They do not work in this example I created: 

https://github.com/nioan/EntitiesAndroidL2CPPSubScenesBug

Works fine in the editor and if the backend is mono, but not with IL2CPP.

I'm using Built Configurations.

**Comment by amigax** [comment]
same issue, even with build configs it wont work,
