### ISSUE TITLE
Spring for LimitedHingeJoint?

### ISSUE THREAD

**Issue by stefanak-michal** [Unity-Technologies/EntityComponentSystemSamples#172]
Hi.

I really like your work on DOTS Physics Joints. But I've one question. Can I set spring for LimitedHingeJoint like the normal unity Hinge Joint has? My goal is to have it pulled (pushed) to some position in entered min and max angle.

My object is Dynamic. I can't use Initial angular velocity, because I've few Hinge Joints chained.

**Comment by amechtley** [comment]
It sounds like what you want are joint motors. These are on the roadmap for Unity Physics but no ETA
