### ISSUE TITLE
How to replicate checkbox 'ConvertToEntity'

### ISSUE THREAD

**Issue by AlbertoZanatta** [Unity-Technologies/EntityComponentSystemSamples#176]
Hi,
Hi, while I was checking the UnityPhysicsSamples Demos in the ECS Samples Github project, I came across this new checkbox inspector option that I'd never seen before - a checkbox labelled as 'ConvertToEntity' and placed just over the Transform component.
This checkbox makes it very easy to select whether or not to convert to ECS entities a whole hierarchy of normal GameObjects - which is precisely what I want to achieve in my own project,
However, I do not know how to make this checkbox/option appear in my own inspector. Is it a customization achieved via a script? Is there a way to add it to the inspector using some in editor commands?
If you know about this, I would really appreciate an answer!
Thanks,
Alberto

**Comment by melMass** [comment]
Hi, 

You might have realized since then, but it's part of the DOTs Editor package - [com.unity.dots.editor](https://docs.unity3d.com/Packages/com.unity.dots.editor@0.8/changelog/CHANGELOG.html)

Cheers

**Comment by Drealmer** [comment]
Indeed, please have a look at "Editor\Conversion\EntityConversionHeader.cs" from the DOTS editor package in your local package cache. Note that this package is currently present in the UnityPhysicsSamples project manifest but not in the ECSSamples one.
