### ISSUE TITLE
How to make GameObject (Terrain,etc.) collides with Entities

### ISSUE THREAD

**Issue by Matrixchung** [Unity-Technologies/EntityComponentSystemSamples#180]
I have tried it before in
[https://docs.unity3d.com/Packages/com.unity.physics@0.3/manual/getting_started.html](url)
But I found that if I add the Convert to Entity and Physics Shape component to Terrain , it will totally disappear while Cube or Sphere do the Conversion in a right way.
My Blocks' EntityArchetype has the following tags: Rotation,RenderBounds,Translation,RenderMesh,PhysicsCollider,LocalToWorld and PhysicsVelocity.
If I create a simple Cube which will be converted to entity, it all works fine with all blocks bouncing on the surface.But when it comes to Terrain (only without entity conversion can I see the rendered Terrain), they just go though the terrain and don't make any collisions.
Can anyone tells me how to make my entities collide with Terrain?

**Comment by snakenjah** [comment]
@Matrixchung  here is a link to the answer and the code used to do it, it's not a nativ solution, its using low level api  https://drive.google.com/drive/folders/1xMqXOHUlsNorgt_Opymeaj4AmTUiODAu?usp=sharing
your welcome
I took it from this tread on Unity forum : https://forum.unity.com/threads/using-unity-terrain-with-dots-workflow.755105/

**Comment by qaisbayabani** [comment]
https://www.youtube.com/watch?v=yIPOCqMYTTg

**Comment by Matrixchung** [comment]
@qaisbayabani @snakenjah Thank you all!
