### ISSUE TITLE
HelloCube ForEach not behaving as expected

### ISSUE THREAD

**Issue by sterlingcrispin** [Unity-Technologies/EntityComponentSystemSamples#181]
Hey I'm trying to dive into this ECS project and understand it but some things are unclear to me

1. If I create a new 3D Object > Cube  , then add _ConvertToEntity_ and _RotationSpeed_ForEach_ component and hit play it rotates just like the example , but if I do the exact same thing with a capsule nothing works. I can't find anything in the code that would explain this.

2. Why is the System not in the scene? How does _RotationSpeedSystem_ForEach_ execute any code if its not a part of the hierarchy? Is there some new UI for assigning code to a scene for ECS?

**Comment by joelpryde** [comment]
1. It should work correctly with a capsule.  Are you sure it isn't just the a capsule looks the same when it is rotated on that axis?
2. By default, systems will operate on all entities that have components that satisfy their queries.  They can be treated as "global" for the most part.  It is the set of components/entities that are created at authoring/run-time that decide which systems get run.
