### ISSUE TITLE
Too much mesh and memory in hello world physics demo

### ISSUE THREAD

**Issue by LittleSylvanas** [Unity-Technologies/EntityComponentSystemSamples#182]
Hi I just start hello world physics scene and come back after 30 min and saw this 686578/2.4GB for meshes in profiler
![EbYC0GWWkAACdST](https://user-images.githubusercontent.com/16510392/85775180-cafd4600-b734-11ea-9f1e-10dc90a10af0.jpg)

**Comment by carpetbagger** [comment]
This is coming from the DisplayColliderSystem which draw the debug colliders in the Hello World scene (i.e. those green lines which can be turned of by toggling the Gizmo option for the view, or disable the viewer in the component on the Physics Settings node in the hierarchy. A fix has also been added to the Unity Physics package for the next release.
![image](https://user-images.githubusercontent.com/8068053/95894669-543a9600-0d81-11eb-8775-f7aa13c944e7.png)
