### ISSUE TITLE
Installation Guide is now incorrect as of 2020.1

### ISSUE THREAD

**Issue by dreasgrech** [Unity-Technologies/EntityComponentSystemSamples#183]
As of 2020.1, the Hybrid Renderer package and Entities package, along with a couple of other packages (deemed deprecated or do not have the intention of being released in the current product cycle) are now being [hidden from the Package Manager](https://blogs.unity3d.com/2020/06/24/package-manager-updates-in-unity-2020-1/).

The ECS package can now be added by adding **com.unity.rendering.hybrid** through the "Add package from git URL..." option in the Package Manager. This Hybrid Renderer package will then add the Entities **com.unity.entities** package as a dependency.

![Package Manager image](https://forum.unity.com/attachments/upload_2020-7-23_19-22-49-png.667328/)

**Comment by Drealmer** [comment]
Thanks for reporting the issue!
The installation guide has been updated as part of this commit https://github.com/Unity-Technologies/EntityComponentSystemSamples/commit/ec16fed3eda2457234c56450b660edb584254e7d
