### ISSUE TITLE
Error while automatic API upgrade

### ISSUE THREAD

**Issue by GazziFX** [Unity-Technologies/EntityComponentSystemSamples#184]
`Assets\Advanced\Boids\Scripts\BoidSystem.cs(45,29): error CS0246: The type or namespace name 'IJobNativeMultiHashMapMergedSharedKeyIndices' could not be found (are you missing a using directive or an assembly reference?)`

Details about used packages and updated code: https://github.com/GazziFX/EntityComponentSystemSamples/commit/b40145717c03bec326761fafedff69243bb05bd3

**Comment by Drealmer** [comment]
It looks like you have updated the packages without updating the samples themselves, as a result you are missing this file in your fork:
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/ECSSamples/Assets/Advanced/Boids/Scripts/MergeSharedKeyIndicesJob.cs
