### ISSUE TITLE
'world' does not contain a definition of 'Allworlds'

### ISSUE THREAD

**Issue by Blackwingbtw** [Unity-Technologies/EntityComponentSystemSamples#185]
'world' does not contain a definition of 'Allworlds'
For the SetBuildConfurationComponenet Script.

**Comment by Drealmer** [comment]
Thanks for your bug report! The problem was subsequently fixed in this commit
https://github.com/Unity-Technologies/EntityComponentSystemSamples/commit/ec16fed3eda2457234c56450b660edb584254e7d
