### ISSUE TITLE
State machine needs to be part of visual graph

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/EntityComponentSystemSamples#188]

**Comment by Drealmer** [comment]
Could you give a bit more context? Are you talking about a sample in particular or a feature in general?

**Comment by laurentopia** [comment]
feature, like bolt 1

**Comment by Drealmer** [comment]
Then you might be interested in DOTS visual scripting, here's a recent forum post detailing our plans there.
https://forum.unity.com/threads/visual-scripting-roadmap-update-september-2020.978732/
Hope this helps, I'm closing this issue now.
