### ISSUE TITLE
Unity 2020.2 UnityWebRequest.isNetworkError is deprecated

### ISSUE THREAD

**Issue by piotr123123123** [Unity-Technologies/EntityComponentSystemSamples#189]
Library\PackageCache\com.unity.entities@0.14.0-preview.19\Unity.Scenes\Hybrid\FileUtilityHybrid.cs(33,21): error CS0618: 'UnityWebRequest.isNetworkError' is obsolete: 'UnityWebRequest.isNetworkError is deprecated. Use (UnityWebRequest.result == UnityWebRequest.Result.ConnectionError) instead.'
I cant update file.

**Comment by Drealmer** [comment]
This bug is now tracked internally, thanks for reporting!
