### ISSUE TITLE
I have no access to the samples

### ISSUE THREAD

**Issue by SirMazius** [Unity-Technologies/EntityComponentSystemSamples#19]
So thats all, i dont know if you have remove the source samples or im not allowed to see them.
anyway would be great to get access to them in order to learn.

Pd Sorry for my english and thanks!

**Comment by MartinGram** [comment]
If you can access this repository, then you by default have access to the samples. Are you looking for anything in particular?

**Comment by SirMazius** [comment]
I was trying to access the ECS rotation example when got a 404 error maybe links are down

**Comment by MartinGram** [comment]
That is correct. The links point to a different repository. It is on the list of things we want to address with future updates to this repository.

**Comment by amechtley** [comment]
Links in the docs should now be fixed in the latest release! Please reopen this issue if you see something that is still wrong.
