### ISSUE TITLE
What is the right way to implement State Machine with Thounds of entities and change frequently

### ISSUE THREAD

**Issue by dongyiqi** [Unity-Technologies/EntityComponentSystemSamples#190]
1. State Machine AI is the good tutorial of implmenting a kinds of FSM  but the question remains
What if we wanted thousands of guards all looking for the player?
If there's a good way to implment it ,Please tell us~ I've been trying to solve such kind of problem for more than 2 years~
thanks

**Comment by Drealmer** [comment]
You'll get very little traction over here, for discussions on how to apply DOTS to various use cases I'd recommend using our forums instead.
https://forum.unity.com/forums/data-oriented-technology-stack.147/
