### ISSUE TITLE
Boid demo build has invisible fish

### ISSUE THREAD

**Issue by aganm** [Unity-Technologies/EntityComponentSystemSamples#192]
I opened in Unity 2020.1.11 and built the boid scene only.

My CPU and GPU usage are correct (close to 100%), but I can't see the fish.
![image](https://user-images.githubusercontent.com/20380758/97811122-761f8e00-1c46-11eb-8490-9824bedd29ce.png)

I can see them in the editor 
![image](https://user-images.githubusercontent.com/20380758/97811144-994a3d80-1c46-11eb-986b-18413f1307c0.png)

**Comment by BrianWill-Unity** [comment]
If you build via the BuildConfiguration asset, it should work. If you build via the main menu "File -> Build and run", it won't. (We don't exactly make this obvious.)

Are you using the BuildConfiguration?

**Comment by aganm** [comment]
I didn't use the BuildConfiguration! I'll try it and report back.

**Comment by BrianWill-Unity** [comment]
I'll close this for now. Let us know if you see the issue with BuildConfiguration.
