### ISSUE TITLE
Installation Guide - Getting Started Missing

### ISSUE THREAD

**Issue by Nanonid** [Unity-Technologies/EntityComponentSystemSamples#20]
Even if Unity abandons this repository, it is still found easily and thus should still either contain or reference  current "Getting Started" documentation.

For example, as of 4/18/2018 only the 2018.1.b12 beta works, not 2018.1.b13, which is confusing and not documented here.

There are some Unity forum posts, but that content should be here as well, or at least explicitly referenced and explained.

**Comment by MartinGram** [comment]
There is an explicit link to the required build in the readme file. The entity component samples are currently in **preview** and have a strict requirement to the linked build. This will change _soon_ or at latests with the launch of 2018.1.

**Comment by Nanonid** [comment]
This doesn't resolve the up to date **Getting Started** issue.

Here is a link to the [README ](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/README.md) Martin mentioned.

Which essentially links to the [Unity ECS Forum](https://forum.unity.com/forums/entity-component-system-and-c-job-system.147/)

And to the [Unity 2018.1.0b12 Beta ](https://beta.unity3d.com/download/ed1bf90b40e6/public_download.html) which as of today AFAIK is the only one that works (which the README doesn't list the versions that work and how to configure them).

I'll just add any notes I think are helpful here for people not wanting to peruse forums.
