### ISSUE TITLE
Suggestion : Archetype interface / struct

### ISSUE THREAD

**Issue by NVentimiglia** [Unity-Technologies/EntityComponentSystemSamples#22]
```
// Same API but slightly more efficient
EntityArchetype archetype = EntityManager.CreateArchetype(ComponentType.Create<MyComponentData>(), ComponentType.Create<MySharedComponent>());
```

This method to create archetypes is going to get messy very fast. 
I can see a list of a dozen typeof`s in the code, yuck.
May I suggest defining archetypes on a struct?

```
struct BetterArcheType : IEntityArchetype
{
   public MyComponentData;
   public MySharedComponent;
   public MyOtherComponenet;
}

EntityArchetype archetype = EntityManager.CreateArchetype<BetterArcheType>();
```

I feel this would be 1) easier to read. 2) Follows the same conventions as the rest of the system. 3) more familiar to us in OOP land.

My only fear is that this might use reflection to identify the parts, but this is happening on bootstrap and can be automated using a weaver technology easy enough, so whatever.

**Comment by amechtley** [comment]
Thanks for the suggestion! I've noted it internally. FWIW we are going to be moving away from reflection over time, so I don't expect we'll go this route specifically, but I do agree the current implementation is a bit clunky

**Comment by amechtley** [comment]
(by the way, feel free to contribute other API usability ideas in [this forum thread](https://forum.unity.com/threads/api-usability.550450/))
