### ISSUE TITLE
Why is it better to copy ComponentDataArray to a NativeArray?

### ISSUE THREAD

**Issue by enzi** [Unity-Technologies/EntityComponentSystemSamples#24]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/0539b0e3b7a8accde154bbee1c52251b4e00278e/Samples/Assets/GameCode/Samples.Dungeon/BoardSystem.cs#L250-L264

I'd iterate on the ComponentDataArray directly. What's the benefit from it?

**Comment by dt665m** [comment]
I had the same question looking at the code, but my guess is at some point the demo will be changed to run some generation in parallel, since there are two copies of practically the same code (Samples.Dungeon and Samples.Dugeon.First)

**Comment by pCYSl5EDgo** [comment]
It's written in Japanese but you can guess.

https://qiita.com/pCYSl5EDgo/items/ff0d872c2585c2e7a2ed

**Comment by davidv-unity** [comment]
Hi! As this is still an _open_ issue: The API has changed quite a bit, here is the recommended way explained: https://www.youtube.com/watch?v=fZfPv-oxO7U&feature=youtu.be&t=32882
Not that in general the `GetNativeArray...` calls do not allocate but provide you with direct access to the underlying buffer, so this is super fast and there is no need to copy the data as you are directly modifying it. If there are questions left, feel free to reopen and leave a small comment.
