### ISSUE TITLE
linux - libncurses.so.5 not found - System.EntryPointNotFoundException: mono_dllmap_insert

### ISSUE THREAD

**Issue by cinch** [Unity-Technologies/EntityComponentSystemSamples#25]
i get these errors when trying to load the packages         
"com.unity.incrementalcompiler": "0.0.38", 
"com.unity.entities": "0.0.12-preview.1":

```
System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception. ---> System.EntryPointNotFoundException: mono_dllmap_insert

DllNotFoundException: Unable to load the unmanaged library `/home/david/.config/unity3d/cache/packages/staging-packages.unity.com/com.unity.burst@0.2.4-preview.2/.Runtime/libburst-llvm.so` Reason: libncurses.so.5: cannot open shared object file: No such file or directory

Unexpected error while trying to initialize the burst JIT compiler: Unexpected exception occured while initializing burst JitCompilerService

```

tested on arch linux with Unity Editor 2018.1.0f2

**Comment by cinch** [comment]
if i install libncurses 5 (from https://aur.archlinux.org/packages/ncurses5-compat-libs/), there's only this error left:

`System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception. ---> System.EntryPointNotFoundException: mono_dllmap_insert`

**Comment by mneilly** [comment]
There appears to be a general problem with library search paths. You can temporarily try working around it by preloading the mono library:

$ (export LD_PRELOAD=/opt/Unity-2018.2.2f1/Editor/Data/MonoBleedingEdge/MonoEmbedRuntime/libmonobdwgc-2.0.so ; /opt/Unity-2018.2.2f1/Editor/Unity)

**Comment by amechtley** [comment]
Hi! I'm curious if you ultimately resolved this issue. FWIW the only distribution of Linux we "officially" support is Ubuntu. That said, if you run into other issues, the best place to get help is probably the [Unity Linux forum](https://forum.unity.com/forums/linux-editor.93/).
