### ISSUE TITLE
How to play animation 3D in pure ECS?

### ISSUE THREAD

**Issue by chris1054** [Unity-Technologies/EntityComponentSystemSamples#26]
I'm trying to use Animation / Animator but still no luck.

**Comment by CodeGize** [comment]
I have the same qustion. In the boid demo, it is using a frag shader to change vertices of the fish mesh to simulate fish swimming.   So it is the only way to aniamtor mesh?

**Comment by ShafinSikder** [comment]
Finally, I found How to play animation with unity ECS
https://www.youtube.com/watch?v=egNHiwsnfF4
