### ISSUE TITLE
Broken Links in cheatsheet.md 

### ISSUE THREAD

**Issue by drstark** [Unity-Technologies/EntityComponentSystemSamples#27]
The links for NativeList and NativeQueue in EntityComponentSystemSamples / Documentation / content / cheatsheet.md are broken. They go to a 404 page. I suggest checking all of the links on that page because I doubt they are the only ones.

**Comment by amechtley** [comment]
Links in the docs should now be fixed in the latest release! Please reopen this issue if you see something that is still wrong.
