### ISSUE TITLE
Missing var keyword

### ISSUE THREAD

**Issue by MrOneTwo** [Unity-Technologies/EntityComponentSystemSamples#28]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/3f2116e38a7da6537e6b738973d9a19e606241f2/TwoStickShooter/Pure/Assets/GameCode/TwoStickBootstrap.cs#L70

Shouldn't it be:
`var Settings = settingsGO?.GetComponent<Settings>();`

**Comment by gabstv** [comment]
```Settings``` is a static variable defined on [line 21](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/3f2116e38a7da6537e6b738973d9a19e606241f2/TwoStickShooter/Pure/Assets/GameCode/TwoStickBootstrap.cs#L21)

**Comment by MrOneTwo** [comment]
I somehow deleted this line and just figured this out... sorry. My bad. Probably should delete this issue then.
