### ISSUE TITLE
Dot Net Standard Support

### ISSUE THREAD

**Issue by NVentimiglia** [Unity-Technologies/EntityComponentSystemSamples#30]
A college has told me that there is a DotNetStandard version of the Unity dlls. He was able to find these dlls in a roundabout way by building the project with 4.6 support. Is there a place where I can find these dlls?

Moreover, does ECS, and specifically Unity.Collections.NativeArray support running on DotNetStandard ? Would like to include these new data structures in a common / dto library.

**Comment by amechtley** [comment]
Hi! Unfortunately the entities package has a dependency on the properties package, which right now does not support .NET Standard 2.0 API. It will be fixed at some point, but for now we'll add this limitation to the documentation (tracking this issue internally)

**Comment by amechtley** [comment]
(I take that back! Latest version of the package should now work fine)
