### ISSUE TITLE
Doesn't support ISharedComponentData inject now?

### ISSUE THREAD

**Issue by CodeGize** [Unity-Technologies/EntityComponentSystemSamples#33]
This is my code. After create a entity with SpawnRandomSharedData and SpawnData, the update function of RandSpawnSystem does not be Called

`public class RandSpawnS : ComponentSystem`
`{`
`    struct Group`
`    {`
`        public int Length;`
`        public EntityArray Entities;`
`        public ComponentDataArray<SpawnData> SpawnDatas;`
`        [ReadOnly] public SharedComponentDataArray<SpawnRandomSharedData> SpawnRandomSharedDatas;`
`    }`
`    [Inject] private Group m_data;`
`    protected override void OnUpdate()`
`    {`
`        Debug.Log("RandSpawnS.OnUpdate");`
`    }`
`}`

**Comment by EricChen1248** [comment]
I do believe Length needs to be 
`public readonly int Length;`
