### ISSUE TITLE
All links in Documentation/content/rotation_example.md are broken

### ISSUE THREAD

**Issue by bellicapax** [Unity-Technologies/EntityComponentSystemSamples#35]
All the links to code and prefabs are broken. I _think_ the entire example may have been removed from the samples? So it really hinders the usefulness of that readme doc because the code inside those links is never shown in the readme.

**Comment by llPekoll** [comment]
Really nice exemple tho,
would be nice to the thinks :/

**Comment by Skybladev2** [comment]
+1, links are broken, please fix it or remove the sample.

**Comment by Skybladev2** [comment]
Hey guys, this repo seems abandoned, but I forked it and fixed rotation sample: https://github.com/Skybladev2/EntityComponentSystemSamples/blob/fix-rotation-sample/Documentation/content/rotation_example.md
Also, I created the pull request #50

**Comment by llPekoll** [comment]
If the repo have been abandoned, they won't validate your pull request I guess,
Btw I tried your fork but it does't work,
I just have 2 entities, and I don't see where you spawn the other ones in the code,
Thanks for trying to help anyways :)

**Comment by MikhailTymchukDX** [comment]
Yeah, I also tried to follow the tutorial. but it's incomplete - there are no systems to work with components.
However, if you download and investigate the example from the [Samples](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/) directory, you will see all needed files.

**Comment by llPekoll** [comment]
thanks @MikhailTymchukDX,
found pretty much everything except `MoveSpeedComponent.cs`
but it seems to be just a variable speed variable, I need too try that.

**Comment by HermitStudio** [comment]
Hi guys,

I've fixed the links on the rotation example page. The files had been moved around in the repository, so the links broke. The changes should propagate through to the public site in the next update/sync.

Thanks for the feedback :D

Corrie

**Comment by HermitStudio** [comment]
Closing issue. The changes aren't live yet but the changes are in the queue.

Corrie
