### ISSUE TITLE
Example features modifying a foreach iteration variable, which raises an error.

### ISSUE THREAD

**Issue by JeromeJ** [Unity-Technologies/EntityComponentSystemSamples#36]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation/content/getting_started.md#componentsystem---a-step-into-a-new-era

Here the code shows this:

        foreach (var e in GetEntities<Group>())
        {
            e.Transform.rotation *= Quaternion.AngleAxis(e.Rotator.Speed * deltaTime, Vector3.up);
        }

But doing this raises this error: `Cannot modify members of 'e' because it is a 'foreach iteration variable'`.

**Comment by davidv-unity** [comment]
Closing this as it's outdated, for more information have a look at the current [samples](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/Samples/Assets/HelloECS) and the [docs](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation~/Readme.md).
