### ISSUE TITLE
Example features trying to modify the return value of a getter, non-setter.

### ISSUE THREAD

**Issue by JeromeJ** [Unity-Technologies/EntityComponentSystemSamples#37]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation/content/ecs_in_detail.md#injection

In the link above, the following code:

    m_Group.Rigidbodies[i].position = m_Group.Position[i].Value;

Which raises: `Cannot modify the return value of 'ComponentArray<Rigibody>.this[int]' because it is not a variable`.

**Comment by davidv-unity** [comment]
Closing this as it's outdated, for more information have a look at the current [samples](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/Samples/Assets/HelloECS) and the [docs](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation~/Readme.md).
