### ISSUE TITLE
Should provide a way to reduce the number of threads

### ISSUE THREAD

**Issue by ofux** [Unity-Technologies/EntityComponentSystemSamples#39]
As a developer using Unity (both for plugins and games), I have done a lot of multithreading in my projects already (I'm not using Unity API in my threads as it's forbidden, but still, I need threads for others heavy and long running computations).
Problem is the job system takes all available CPU cores and my own classical threads may create contention.

I think I'm not the only one in this situation. It would be great if we could reduce the number of threads taken by the Job system, or even better, get access to the thread pool of the job system in order to pick up some thread for classical multithreading.

**Comment by martindevans** [comment]
We have a similarproblem in our asset [Dissonance Voice Chat](https://assetstore.unity.com/packages/tools/audio/dissonance-voice-chat-70078) - we've got a background thread which preprocesses and encodes the audio, this is obviously fairly latency sensitive and ideally wouldn't be contending with other threads for hardware resources.

Ideally I think we'd want two things:

1. A way to pin standard threads to certain cores. So in this case we could pin the Dissonance thread to a particular core. Perhaps something like [SetProcessorAffinity](https://msdn.microsoft.com/en-us/library/system.threading.thread.setprocessoraffinity.aspx?f=255&MSPPError=-2147217396) could be exposed for "classic" threads.
2. A way to exclude job system threads from certain cores. So we can exclude the job system from scheduling anything which may contend with the encoding thread. Perhaps something like [ProcessorAffinity](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processoraffinity?redirectedfrom=MSDN&view=netframework-4.7.2#System_Diagnostics_Process_ProcessorAffinity) could be exposed for Job system threads.

**Comment by amechtley** [comment]
Thanks for the suggestion! I've added this issue to our internal tracker
