### ISSUE TITLE
Cannot open 'Pure' sample project, Unity hangs

### ISSUE THREAD

**Issue by MorrisonCole** [Unity-Technologies/EntityComponentSystemSamples#43]
**OS**: Windows 10

**Unity Versions**: 2018.1.0f2, 2018.1.1f1, 2018.1.6f1, 2018.2.0b10

*Reproduction*:
* On a fresh checkout of this repository open `TwinStickShooter/Pure` in Unity

*Symptoms*:
* Unity hangs at 'Compiling Assembly Definition Files scripts':
![image](https://user-images.githubusercontent.com/963368/42085807-4e3ecc08-7b89-11e8-964c-baef43e307fb.png)
* Last significant line in `%LOCALAPPDATA%/Unity/Editor/Editor.log` is always `Cannot transition thread 00002D10 from ASYNC_SUSPEND_REQUESTED with ASYNC_SUSPEND_REQUESTED`.
* [Editor.log](https://github.com/Unity-Technologies/EntityComponentSystemSamples/files/2148882/Editor.log) from an attempt with Unity 2018.1.0f2

*Things I've tried*:
* Using the latest incremental compiler `0.0.42-preview.9`
* Using an older version of the incremental compiler `0.0.29`

**Comment by MorrisonCole** [comment]
OK, a workaround is to downgrade the `com.unity.entities` package to `0.0.12-preview.4` from `0.0.12-preview.6`. `0.0.12-preview.6` seems to be broken.

**Comment by MorrisonCole** [comment]
@sinhadanish I didn't actually try that so it's possible it's broken even further. I was just using the project to inspect the scene.

**Comment by sinhadanish** [comment]
I am trying to build parts of my game so that I can shift early on. 
@MorrisonCole

**Comment by jessicafalk** [comment]
Using the latest incremental compiler (`0.0.42-preview.14)` together with the latest entities package (`0.0.12-preview.8`) seems to fix this issue.

**Comment by amechtley** [comment]
Glad this issue got resolved!
