### ISSUE TITLE
How do you do colissions in ECS?

### ISSUE THREAD

**Issue by njbrown09** [Unity-Technologies/EntityComponentSystemSamples#45]
How do you do things like OnCollisionEnter in pure (or hybrid) ecs?

**Comment by keeganstothert** [comment]
i have the same question. i tried this hybrid approach:

```csharp
namespace Component {
  public class Collision : MonoBehaviour {
    [HideInInspector]
    public CollisionState state;
    [HideInInspector]
    public GameObject source;
    [HideInInspector]
    public Collision2D other;

    public void OnCollisionEnter2D (Collision2D other) {
      setCollision(other, Component.CollisionState.enter);
    }

    public void OnCollisionExit2D (Collision2D other) {
      setCollision(other, Component.CollisionState.exit);
    }

    public void OnCollisionStay2D (Collision2D other) {
      setCollision(other, Component.CollisionState.stay);
    }

    void setCollision (Collision2D other, Component.CollisionState state) {
      Component.Collision collision = GetComponent<Collision>();
      if (!collision) {
        return;
      }

      collision.state = state;
      collision.source = gameObject;
      collision.other = other;
    }
  }

  public enum CollisionState {
    enter,
    exit,
    stay
  }
}
```

and a damage system like this

```csharp

[UpdateBefore(typeof(UnityEngine.Experimental.PlayerLoop.FixedUpdate))]
public class Damage : ComponentSystem {
  struct Components {
    public Component.Collision collision;
    public Component.Health health;
  }

  // runs every frame
  protected override void OnUpdate () {
    foreach (var e in GetEntities<Components>()) {
      if (e.collision.state != Component.CollisionState.exit
        || e.collision.other == null
        || e.collision.other.gameObject.tag != "Ball") {
        return;
      }

      e.health.value--;
    }
  }
}
```

but it has inconsistent results

**Comment by kudorado** [comment]
CollisionEmitter
```using Unity.Entities;
using UnityEngine;

namespace BallJump{
	public class PlayerColliderSystem : ComponentSystem{

		public struct Group{
			public readonly int Length;
			public EntityArray Entity;
			public  ComponentArray<Rigidbody> Body;
			public ComponentDataArray<ColliderData> Collider;
			public ComponentArray<PlayerMovementData> Movement;
		}


		[Inject] private Group Data;
		protected override void OnUpdate()
		{
			for (int i = 0; i < Data.Length; i++)
			{
				var puc = PostUpdateCommands;
				var entity = Data.Entity[i];

				switch(Data.Collider[i].colliderData){
					case ColliderObject.Data.Cube:
						Data.Body[i].velocity = Vector3.up * Data.Movement[i].BounceForce;
						break;
					case ColliderObject.Data.Obstacle:
						Time.timeScale = 0;
						break;
				}

				puc.RemoveComponent<ColliderData>(entity);
			}

		}
	}


}

```
ColliderObject 
```

public class ColliderObject : MonoBehaviour {

      
        public Data data;
        public enum Data
        {
            Cube,
            Obstacle,

        }
    
}
```
PlayerCollisionSystem 
```
using Unity.Entities;
using UnityEngine;

namespace BallJump{
	public class PlayerColliderSystem : ComponentSystem{

		public struct Group{
			public readonly int Length;
			public EntityArray Entity;
			public  ComponentArray<Rigidbody> Body;
			public ComponentDataArray<ColliderData> Collider;
			public ComponentArray<PlayerMovementData> Movement;
		}


		[Inject] private Group Data;
		protected override void OnUpdate()
		{
			for (int i = 0; i < Data.Length; i++)
			{
				var puc = PostUpdateCommands;
				var entity = Data.Entity[i];

				switch(Data.Collider[i].colliderData){
					case ColliderObject.Data.Cube:
						Data.Body[i].velocity = Vector3.up * Data.Movement[i].BounceForce;
						break;
					case ColliderObject.Data.Obstacle:
						Time.timeScale = 0;
						break;
				}

				puc.RemoveComponent<ColliderData>(entity);
			}

		}
	}


}
```

**Comment by keeganstothert** [comment]
first I convert the event from the old event system to an ecs event which i call "eventities" because they only live for one frame. The Monobehaviour looks like this

`
  public class ImpactEventManager : MonoBehaviour {
    Entity entity;
    EntityManager em;

    void OnEnable () {
      entity = gameObject.GetComponent<GameObjectEntity>().Entity;
      em = World.Active.GetExistingManager<EntityManager>();
    }

    void OnCollisionEnter2D (Collision2D collision) {
      AddOrUpdateImpact(collision, Overlap.Enter);
    }

    void OnCollisionStay2D (Collision2D collision) {
      AddOrUpdateImpact(collision, Overlap.Stay);
    }

    void OnCollisionExit2D (Collision2D collision) {
      AddOrUpdateImpact(collision, Overlap.Exit);
    }

    void AddOrUpdateImpact (Collision2D collision, State.Overlap newState) {
      var collidingEntity = collision.gameObject.GetComponent<GameObjectEntity>().Entity;

      if (!em.HasComponent<Impact>(collidingEntity)) {
        em.AddComponent(collidingEntity, typeof(Impact));
      }

      em.SetComponentData<Impact>(collidingEntity, new Impact {
        State = newState,
        OtherEntity = entity,
        Collision = new CollisionData(collision)
      });
    }
  }
`

I use an enum to track the states

` public enum Overlap {
    Enter,
    Stay,
    Exit
  }`

In the component I destructure the collision object into blittable data, you can peel more things of the collision object as the need arises.

`
  public struct Impact : IComponentData {
    public Entity OtherEntity;
    public State.Overlap State;
    public CollisionData Collision;
  }


  public struct CollisionData {
    public CollisionData (Collision2D collision) {
      // deconstruct any collision data into blittable data here
      Contact = collision.contactCount > 0 ? new Contact(collision.GetContact(0)) : new Contact { };
    }
    public Contact Contact;

  }

  public struct Contact {
    public Contact (ContactPoint2D contactPoint) {
      Point = contactPoint.point;
      RelativeVelocity = contactPoint.relativeVelocity;
      Normal = contactPoint.normal;
    }

    public float2 Point;
    public float2 RelativeVelocity;
    public float2 Normal;
  }`

Now systems can simply look for the impact component and find out what they impacted with by reading the OtherEntity value. Below is an example of how to take damage.

`  [UpdateBefore(typeof(ImpactCleanupSystem))]
public class FrictionZoneSystem : ComponentSystem {
    struct Data {
      public readonly int Length;
      public ComponentDataArray<Health> Health;
      public ComponentDataArray<Impact> Impact;
      public EntityArray Entity;
    }

    [Inject] Data data;

    protected override void OnUpdate () {
      for (var i = 0; i < data.Length; i++) {
        if(EntitiyManager.HasComponent<Damage>(data.Impact[i].OtherEntity)) {
          EntityManager.SetComponentData<Health>(data.Entity[i], new Health {
            Value = data.Health[i].Value - EntityManager.GetComponentData<Damage>(data.Impact[i].OtherEntity)
          });
        }
      }
    }
  }`

Finally an impact cleanup system runs at the end of every frame

` public class ImpactCleanupSystem : ComponentSystem {
    struct Data {
      public readonly int Length;
      public ComponentDataArray<Impact> Impact;
      public EntityArray Entity;
    }
    [Inject] Data data;

    protected override void OnUpdate () {
      for (var i = 0; i < data.Length; i++) {
        PostUpdateCommands.RemoveComponent<Impact>(data.Entity[i]);
      }
    }
  }`

This works for triggers as well and can be adapted to convert all old scool events into "eventities". The big drawback right now is not being able to collide with two things in one frame due to the one component per type on entities rule. This could be fixed later if we ever get arrays on non shared components or maybe by using a bufferarray.

**Comment by tbriley** [comment]
@keeganstothert regarding the one component type per entity rule: in the past in my own ECS system i would pack these into a collection component, in this example a CollisionCollectionComponent. with unity ecs we can use IBufferElementData instead.

**Comment by whuop** [comment]
Great tips here, I avoid the impact Cleanup system entirely using barriers to schedule a component removal at that barriers synchronization point instead. Expanding this thread with my own Impact emitter that i made based on the things posted here =) 

The impact emitter, which creates impacts that can be handled with pure ECS. The PostLateUpdate barrier is a barrier system i made myself which simply synchronizes as late as possible during the frame. 
```
using ECS.Components.Physics;
using Unity.Entities;
using UnityEngine;
using Whuop.ECS.Barriers;

namespace Physics
{
    [RequireComponent(typeof(GameObjectEntity))]
    [RequireComponent(typeof(Rigidbody))]
    public class ImpactEmitter : MonoBehaviour
    {
        private GameObjectEntity m_goEntity;
        private EntityManager m_eManager;

        private PostLateUpdateBarrier m_barrier;

        private void OnEnable()
        {
            m_goEntity = GetComponent<GameObjectEntity>();
            m_eManager = m_goEntity.EntityManager;

            m_barrier = m_eManager.World.GetOrCreateManager<PostLateUpdateBarrier>();
        }

        private void OnCollisionEnter(Collision collision)
        {
            AddOrUpdateImpact(collision);
        }

        private void AddOrUpdateImpact(Collision collision)
        {
            var otherGoEntity = collision.collider.transform.root.GetComponent<GameObjectEntity>();
            Entity otherEntity = new Entity { Index = -1, Version = -1 };
            if (otherGoEntity != null)
                otherEntity = otherGoEntity.Entity;

            if (!m_eManager.HasComponent<ECS.Components.Physics.Impact>(m_goEntity.Entity))
            {
                m_eManager.AddComponentData(m_goEntity.Entity, new Impact { Impulse = 0.0f, RelativeVelocity = 0.0f, OtherEntity = otherEntity });
                m_eManager.AddBuffer<ImpactPoint>(m_goEntity.Entity);
            }

            var buffer = m_eManager.GetBuffer<ImpactPoint>(m_goEntity.Entity);

            m_eManager.SetComponentData(m_goEntity.Entity, new ECS.Components.Physics.Impact
            {
                Impulse = collision.impulse,
                RelativeVelocity = collision.relativeVelocity,
                OtherEntity = otherEntity
            });

            for(int i = 0; i < collision.contactCount; i++)
            {
                var contact = collision.contacts[i];
                buffer.Add(new ImpactPoint
                {
                    Point = contact.point,
                    Normal = contact.normal,
                    Separation = contact.separation,
                    OtherEntity = otherEntity
                });
            }

            var cmd = m_barrier.CreateCommandBuffer();
            cmd.RemoveComponent<Impact>(m_goEntity.Entity);
            cmd.RemoveComponent<ImpactPoint>(m_goEntity.Entity);
        }
    }
}
```

The Impact struct, and the ImpactPoint struct. The impact struct is a blittable version of the Collision class, and the ImpactPoint is a blittable version of the ContactPoint struct. 
```
using Unity.Entities;
using Unity.Mathematics;

namespace ECS.Components.Physics
{
    public struct Impact : IComponentData
    {
        public float3 Impulse;
        public float3 RelativeVelocity;

        public Entity OtherEntity;
    }

    public struct ImpactPoint : IBufferElementData
    {
        public float3 Point;
        public float3 Normal;
        public float Separation;

        public Entity OtherEntity;
    }
}
```

And that's all there is to it, no Cleanup system needed as i told my barrier system which synchronizes at the end of the frame to remove my Impact struct and ImpactPoint buffer from the Entity.

**Comment by davidv-unity** [comment]
Note that `Unity.Physics` is now available now via the package manager as a preview package while the samples can be found [here](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/UnityPhysicsExamples/Assets/Demos).

**Comment by Ph0t0nX** [comment]
> Note that `Unity.Physics` is now available now via the package manager as a preview package while the samples can be found [here](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/UnityPhysicsExamples/Assets/Demos).

404

**Comment by carnoxen** [comment]
> > Note that `Unity.Physics` is now available now via the package manager as a preview package while the samples can be found [here](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/UnityPhysicsExamples/Assets/Demos).
> 
> 404

i think it is here: https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/UnityPhysicsSamples/Assets/Demos
