### ISSUE TITLE
ComponentDataWrapper is deprecated?

### ISSUE THREAD

**Issue by Thaina** [Unity-Technologies/EntityComponentSystemSamples#46]
I got this error today

> The type or namespace name 'ComponentDataWrapper<>' could not be found (are you missing a using directive or an assembly reference?)

And it seem like I can't find reference about `ComponentDataWrapper<>` in this repo anymore. Is it deprecated or something?

**Comment by amechtley** [comment]
Hi! Sorry this issue was never responded to. I hope since you didn't follow up that the problem went away. I'll close this issue for now, but feel free to reopen it if you're still seeing this problem.

**Comment by billbarsch** [comment]
The type or namespace name 'ComponentDataWrapper<>' could not be found
Same problem here

**Comment by amechtley** [comment]
If you are in the latest release, please note that `ComponentDataWrapper<T>` has been renamed `ComponentDataProxy<T>`. (See [release notes](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/ReleaseNotes.md))

**Comment by Prog-Maker** [comment]
> (See [release notes](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/ReleaseNotes.md))

Where? last version 0.0.22
But new version 0.0.24

**Comment by EIZENHORN91** [comment]
It’s samples version. Samples 0.0.22 == Entities 0.0.24
