### ISSUE TITLE
Error about package manager version

### ISSUE THREAD

**Issue by Kill-Console** [Unity-Technologies/EntityComponentSystemSamples#47]
In manifest.json:
"com.unity.package-manager-ui": "2.0.0-preview.3"
will occur an error when open the project in samples
If I change this to 1.9.11, it will be OK.

**Comment by amechtley** [comment]
Hi! Sorry no one replied to this issue more promptly. I'm hoping you managed to get it resolved. Please feel free to reopen this issue if it is still giving you problems (it was likely package-manager related)
