### ISSUE TITLE
sample documentation needs update to preview 12

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/EntityComponentSystemSamples#56]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation/content/getting_started.md

outdated:
Schedule(this, 64, inputDeps);
struct RotationSpeedRotation : IJobProcessComponentData<Rotation, RotationSpeed>

**Comment by davidv-unity** [comment]
Hi and thank you, I'm closing this as it is indeed outdated, details on how do do approach this can be found in the [samples](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/Samples/Assets/HelloECS) and the [docs](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation~/Readme.md).
