### ISSUE TITLE
links are dead in rotation tuto

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/EntityComponentSystemSamples#57]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation/content/rotation_example.md

**Comment by HermitStudio** [comment]
Hi Laurent,

I've fixed the links on the rotation example page. The changes should propagate through to the public site in the next update/sync.

Thanks for the feedback :D 

Corrie

**Comment by HermitStudio** [comment]
Closing issue.
