### ISSUE TITLE
how to disable a system in runtime

### ISSUE THREAD

**Issue by liuhaopen** [Unity-Technologies/EntityComponentSystemSamples#58]
I have two systems that control the same components, and I only need one of them to be enabled at the same time.

**Comment by EIZENHORN91** [comment]
World.Active.GetOrCreateManager<YourSystem>().Enabled = false;

**Comment by liuhaopen** [comment]
thanks for answer, it works! the complete code is : World.Active.GetOrCreateManager\<system that needs to be disable\>().Enabled = false;text inside <> will be hide, I use \\< text\\>
