### ISSUE TITLE
Question regarding the use of bool in IComponentData

### ISSUE THREAD

**Issue by PMcGoldrick** [Unity-Technologies/EntityComponentSystemSamples#63]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/89c6a5c0f97e170a8494fd1d17376d21b846eff5/Samples/Assets/TwoStickShooter/Pure/Scripts/ComponentTypes.cs#L13

What witchcraft is this?! When I try to use a `System.Boolean` in my components I receive a fatal error regarding it not being blittable. This may be a novice question, but I'd appreciate any explanation that can be offered.

**Comment by amechtley** [comment]
Thanks for answering, @pCYSl5EDgo ! If you have any other questions like this, @PMcGoldrick , please feel free to reach out on the [forums](https://forum.unity.com/forums/entity-component-system-and-c-job-system.147/) :)

**Comment by PMcGoldrick** [comment]
Will use the forums next time. Sorry for the noise here.

**Comment by amechtley** [comment]
No worries on noise! It's just that this area doesn't get nearly as much traffic (from the community or from devs), so you're likely to get better turnaround on the forums :)
