### ISSUE TITLE
Unable to access SharedComponentDataArray in JobProcessComponentData/JobParallelFor

### ISSUE THREAD

**Issue by AnibersStudio** [Unity-Technologies/EntityComponentSystemSamples#64]
Hello,
I encountered what the title describes recently.
On the one hand, SharedComponent cannot be in the type parameters of JobProcessComponentData.
On the other hand, if I pass a SharedComponentDataArray to a  ParallelFor job, Burst complains about getting SharedComponent from List<SharedComponent>. It seems that this relates to EntityManager.GetAllUniqueSharedComponentData who accept List<T> as a out parameter.
So is this intended? I just can't access SharedComponent in jobs, must iterate over all unique ones and schedule jobs per SharedComponent? Or did I miss some content in the doc?
Thanks and please pardon my English.

**Comment by AnibersStudio** [comment]
Now I just copy data of SharedComponent to a NativeArray before schedule jobs. Can this copy be avoided?

**Comment by macton** [comment]
That is the correct solution. SharedComponent are class and not intended to be used in jobs and not burst compatible.
