### ISSUE TITLE
Unity shuts down when I try to open the project

### ISSUE THREAD

**Issue by mcotomx** [Unity-Technologies/EntityComponentSystemSamples#65]
I cloned the repository and try to open the Samples folder in Unity, but it crashes. I've tried it with Unity 2018.10.2f1 and also Unity 2018.2.3f1 (which I think is the last version used in the repository). 

When I delete the packages manifest I'm able to open the project, but it doesn't compile.

When I use the manifest provided in the [repo](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Samples/Packages/manifest.json) the project crashes and I'm unable to open it again.

I've tried to download the packages directly in the Packages Window but it doesn't work either.

**Comment by EIZENHORN91** [comment]
You must use latest beta (2018.3)
![image](https://user-images.githubusercontent.com/25122510/46781456-6add2b00-cd2a-11e8-9624-b09f5fecb6da.png)

**Comment by mcotomx** [comment]
I downloaded 2018.3.0b5 but it's the same problem: If I try to use the repo manifest unity crashes (it doesn't matter if I place the manifest with the project closed or open), if I delete the manifest the project opens but with lots of references broken. :(

**Comment by davidv-unity** [comment]
Hi & thank you for reporting, this is all fixed in the latest version - just follow the [Installation guide](https://github.com/Unity-Technologies/EntityComponentSystemSamples#installation-guide-for-blank-ecs-project).
