### ISSUE TITLE
[Minor] Phyllotaxis: Overkill reference to EntityManager

### ISSUE THREAD

**Issue by sfwhite** [Unity-Technologies/EntityComponentSystemSamples#66]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/247d15efc215ac4a3f2efb043667cd8cce0fec5d/Samples/Assets/Phyllotaxis/Scripts/Bootstrap.cs#L26-L27

```csharp
rotationFocus = entityManager.CreateArchetype(typeof(Position),typeof(Rotation),typeof(RotationSpeed), typeof(RotationFocus));
```

**Comment by macton** [comment]
N/A - This sample has been removed.
