### ISSUE TITLE
cheatsheet, add one line to explain each type

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/EntityComponentSystemSamples#68]
we don't need namespace of type because these are automatically solved by Rider & VS
what would help is this:
| EntityArchetype |  unique array of ComponentType, used to group entities

**Comment by davidv-unity** [comment]
Hi, just browsing the issues and I think [this](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation~/cheatsheet.md) might be what you are looking for, otherwise feel free to reopen this issue.

**Comment by laurentopia** [comment]
No that's not it, this shows the type of the struct, not the purpose.

**Comment by davidv-unity** [comment]
Agree. The docs are to sparse on that although there are some samples available.

**Comment by leethomason** [comment]
That could certainly be better. Tracking internally issue 1160292. Closing this external issue.
