### ISSUE TITLE
Bad performance of EndFrameTransformSystem

### ISSUE THREAD

**Issue by roygear** [Unity-Technologies/EntityComponentSystemSamples#69]
I am using Unity 2018.2.9f1 for testing, and no changing for the example.

In the `TwoStickPure` scene, I just let my jet skip the missiles. Bad performance caused by the `ComponentChunkIterator:GatherChunksJob` in `EndFrameTransformSystem` . 

How to fix this?
![c](https://user-images.githubusercontent.com/30362268/46935192-0fde6780-d08d-11e8-95a2-e7ac96573060.jpg)

**Comment by justonia** [comment]
I've also noticed this system allocates a lot of GC memory.

**Comment by StewMcc** [comment]
EndFrameTransformSystem (2018.3.6f1 - 0.0.12-24), seems to have a lot of GC Alloc in general? 
![endframetransform-gc](https://user-images.githubusercontent.com/8014812/53287567-f0132a80-3775-11e9-9caf-37fea1c21562.png)

Have 10,000 renderable entities in the scene (instanced) and GC ticks from this cause quite big spikes in FPS.

Any way of reducing this on my end, prime causes of the Alloc's?

**Comment by leethomason** [comment]
Being tracked internally in issue 1160290. Closing this external issue.
