### ISSUE TITLE
Entire project is not working on 2018.1.0b11.

### ISSUE THREAD

**Issue by yasuohasegawa** [Unity-Technologies/EntityComponentSystemSamples#7]
Newest beta version of editor is 2018.1.0b11, but I've got an error below.

Assembly has reference to non-existent assembly 'Unity.Burst'

Probably I need to get "2018.1.0b12" editor but where can i find it?

**Comment by davidpol** [comment]
That is right; you need to use the beta downloadable from [here](https://forum.unity.com/threads/welcome.522627/).

**Comment by yasuohasegawa** [comment]
Thanks! I've found it.
