### ISSUE TITLE
README.md Installation Guide doesn't work

### ISSUE THREAD

**Issue by chbfiv** [Unity-Technologies/EntityComponentSystemSamples#72]
Needed to "check" preview packages before you can see "Entities". 

After installing Entities Unity crashes and will continue to crash until you remove the new package from the manifest.json

4.x was already selected.

I tried installing various packages that might be dependencies, but it's still crashing.

jobs, collections, mathematics, boost, ...

**Comment by sterlingcrispin** [comment]
@chbfiv just ran into the same problem did you find a solution? I tried to import version 0.0.12 into Unity 2018.3.0b9 and Unity crashed + crashes every time the project is reopened. I can't find any documentation about release version 0.0.12 or what version the readme was written for

**Comment by bsgbryan** [comment]
I don't know if this is helpful but, I had the same issue on 2018.3.0b9. Both 2018.2.15f1 and 2019.1.0a8 boot successfully.

It's important to note that the structure of the entities 0.0.12 preview.19 is quite different from what seems to documented everywhere. For example, the `MoveSpeed` and `MoveForward` components do not exist in either the `Unity.Entities` or the `Unity.Transforms` namespaces. Neither does `MoveForwardSystem`.

`MoveSpeed` and `MoveForward` exist in the TwinStickShooter sample project's [ComponentTypes.cs](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Samples/Assets/TwoStickShooter/Pure/Scripts/ComponentTypes.cs) file. `MoveForwardSystem` is defined in [MoveForwardSystem.cs](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Samples/Assets/TwoStickShooter/Pure/Scripts/MoveForwardSystem.cs). The main tutorial on Unit Testing in ECS states that all of these resources are included either the `Unity.Entities` or `Unity.Transforms` namespaces - they are not.

In general, documentation on ECS seems sparse and fairly out of date (_for example, I cannot get the Unity.Entities.Tests.dll to load for the life of me - but everywhere assumes it exists and loads without any problems_).

I am currently running Unity 2019.1.0a8 with only the following Package Manager packages installed:

* Burst: _0.2.4-preview.37_
* Collections: _0.0.9-preview.9_
* Entities: _0.0.12-preview.19_
* IncrementalCompiler: _0.0.42-preview.24_
* Jobs: _0.0.7-preview.5_
* Mathematics: _0.012-preview.19_
* Package Manager UI: _2.1.0-preview.1_

Below are the updates I needed to make to InfallibleCode's tutorial on[ Unit Testing ECS](http://infalliblecode.com/test-unity-ecs/) (_comments mine_):

```csharp
using NUnit.Framework;

using UnityEngine; // This is required because we call Time.deltaTime below

using Unity.Entities;
using Unity.Mathematics;
using Unity.Transforms;
using Unity.Burst;  // This is required because we use the [BurstCompile] attribute - which you'll also see called [ComputeJobOptimization]. [BurstCompile] replaces [ComputeJobOptimization]. [ComputeJobOptimization] is now obsolete (This is an example demonstrating how significantly things are changing in ECS
using Unity.Jobs; // We need this because MoveForwardSystem uses JobComponentSystem, which is just ComponentSystem with added support for Unity's new C# Jobs.
using Unity.Collections;  // We need this because we use the ComponentDataArray type below. This is one of the new collection types ECS uses.

namespace Tests
{
  // Here is where we define MoveSpeed. Again, even though some places say it is included as part of ECS, it is not.
  public struct MoveSpeed : IComponentData
  {
    public float speed;
  }

  // This is the other missing component. This is what's called a "Tag" component - it doesn't do anything, it just exists as a tag, or marker, to make organizing component data a bit more logical and easier to understand.
  public struct MoveForward : IComponentData { }

  // Here is the system we actually want to test. Again, this is not included in ECS - even though some blog posts and videos say it is (was).
  // Notice the use of JobComponentSystem. This system uses Unity's C# Jobs - meaning it supports multithreading.
  public class MoveForwardSystem : JobComponentSystem
  {
    // Here is where we specify we want to use the Burst compiler. If we commented this out we could remove the "using Unity.Burst" line above.
    [BurstCompile]
    // This is the codeUnity actually runs on multiple threads
    struct MoveForwardRotation : IJobParallelFor
    {
      public ComponentDataArray<Position> positions;
      [ReadOnly] public ComponentDataArray<Rotation> rotations;
      [ReadOnly] public ComponentDataArray<MoveSpeed> moveSpeeds;
      public float dt;

      // This method is called from any thread running our MoveForwardSystem
      public void Execute(int i)
      {
        positions[i] = new Position {
          Value = positions[i].Value + (dt * moveSpeeds[i].speed * math.forward(rotations[i].Value))
        };
      }
    }

    ComponentGroup m_MoveForwardGroup;

    protected override void OnCreateManager()
    {
      m_MoveForwardGroup = GetComponentGroup(
          ComponentType.ReadOnly(typeof(MoveForward)),
          ComponentType.ReadOnly(typeof(MoveSpeed)),
          ComponentType.ReadOnly(typeof(Rotation)),
          typeof(Position));
    }

    protected override JobHandle OnUpdate(JobHandle inputDeps)
    {
      var moveForwardJob = new MoveForwardRotation {
        positions = m_MoveForwardGroup.GetComponentDataArray<Position>(),
        rotations = m_MoveForwardGroup.GetComponentDataArray<Rotation>(),
        moveSpeeds = m_MoveForwardGroup.GetComponentDataArray<MoveSpeed>(),
        dt = Time.deltaTime
      };

      var moveForwardJobHandle = moveForwardJob.Schedule(
        m_MoveForwardGroup.CalculateLength(), 
        64, 
        inputDeps);
      
      return moveForwardJobHandle;
    }
  }

  // Here is the actual test class
  [TestFixture]
  [Category("Unity ECS Tests")]
  public class MoveForwardSystemTests
  {
    // BEGIN: Code I copied from Unity.Entities.Tests.ECSTestFixtures. For the life of me, I was unable to get Unity.Entities.Tests linked and working properly.
    protected World m_PreviousWorld;
    protected World World;
    protected EntityManager m_Manager;
    protected EntityManager.EntityManagerDebug m_ManagerDebug;

    protected int StressTestEntityCount = 1000;

    [SetUp]
    public virtual void Setup()
    {
      m_PreviousWorld = World.Active;
      World = World.Active = new World("Test World");

      m_Manager = World.GetOrCreateManager<EntityManager>();
      m_ManagerDebug = new EntityManager.EntityManagerDebug(m_Manager);
    }

    [TearDown]
    public virtual void TearDown()
    {
      if (m_Manager != null)
      {
        World.Dispose();
        World = null;

        World.Active = m_PreviousWorld;
        m_PreviousWorld = null;
        m_Manager = null;
      }
    }
    // END: Code I copied from Unity.Entities.Tests.ECSTestFixtures.

    // This test pulls everything together and tells us everything ECS needs is wired up correctly and ready to go!
    [Test]
    public void When_MoveSpeedEqualsZero_Then_EntityDoesntMove()
    {
      // arrange
      var entity = m_Manager.CreateEntity(
          typeof(MoveForward),
          typeof(MoveSpeed),
          typeof(Position),
          typeof(Rotation));
      m_Manager.SetComponentData(entity, new MoveSpeed { speed = 0 });
      m_Manager.SetComponentData(entity, new Position { Value = new float3(0, 0, 0) });
      m_Manager.SetComponentData(entity, new Rotation { Value = new quaternion(0, 0, 0, 0) });

      // act
      World.CreateManager<MoveForwardSystem>().Update();

      // assert
      Assert.AreEqual(new float3(0, 0, 0), m_Manager.GetComponentData<Position>(entity).Value);
    }
  }
}
```

With the packages listed above on Unity 2019.1.0.a8 I can use the Test Runner in EditMode to run this test successfully - which tells me my testing environment and ECS setup is working correctly.

When Unity started crashing on load for me I did create a new project. First I removed all Package Manager packages - all of them. Then I added them back one-by-one until all compile errors in my test script went away.

I'd be very interested to see how/if this configuration and code work in Unity 2018.3.0b9.

I hope this helps!

**Comment by davidv-unity** [comment]
Hi, following the new guide should work for everyone now, please reopen this if you still encounter any issues! Kind Regards!
