### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/EntityComponentSystemSamples#74]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation/reference/world.md

**Comment by davidv-unity** [comment]
Hi & thanks for reporting! There has been heavy restructuring, [this](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation~/cheatsheet.md) points [here](https://docs.unity3d.com/Packages/com.unity.entities@0.0/api/Unity.Entities.World.html) now. 
Kind regards!
