### ISSUE TITLE
Broken Links in the Capsicum cheat sheet - 11/09/2018

### ISSUE THREAD

**Issue by ArturoNereu** [Unity-Technologies/EntityComponentSystemSamples#75]
All references to .../Samples/Packages/... are missing as the Packages folder is now empty.

**Comment by davidv-unity** [comment]
Hi & thank you for reporting, this has been restructured, the documentation can be found [here](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation~/index.md) while the ecs samples can be found [here](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/Samples/Assets) and the physics samples are located [here](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/UnityPhysicsExamples/Assets).
