### ISSUE TITLE
Tutorial documentation possibly out of date.

### ISSUE THREAD

**Issue by AndyJBuchananWISH** [Unity-Technologies/EntityComponentSystemSamples#78]
Just noticed https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation/content/two_stick_shooter.md
talks of inability to add a Shared component  on command buffer, but actual code seems to do just that.

**Comment by davidv-unity** [comment]
Hi, you are correct. This sample has been deprecate. You can find the current ecs samples [here](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/Samples/Assets) and the current physics samples [here](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/UnityPhysicsExamples/Assets). Kind regards!
