### ISSUE TITLE
index.md lost a link

### ISSUE THREAD

**Issue by OneYoungMean** [Unity-Technologies/EntityComponentSystemSamples#79]
![tim 20181122224304](https://user-images.githubusercontent.com/44113189/48909466-4dae8700-eea8-11e8-9c9c-7ef9194872df.png)

**Comment by davidv-unity** [comment]
Hi, this has been changed and it's working - although I just found a small issue that the lower links both link to the index instead of the respective sub section (can be selected on the left). This will be fixed with the next public release.
