### ISSUE TITLE
Enum in ComponentDataWrapper don't get set on ComponentData

### ISSUE THREAD

**Issue by Ziboo** [Unity-Technologies/EntityComponentSystemSamples#8]
I tried something like that:
```
public enum FactionType
{
	Friendly,
    Enemy
}

[Serializable]
public struct Faction : IComponentData
{
	public FactionType Value;
}

public class FactionComponent : ComponentDataWrapper<Faction>
{
}
```
But changing the Value on the FactionComponent doesn't change it on the Entity ComponentData.
I though I was doing something wrong...

I checked the "MeshInstanceRendererComponent" which has a ShadowType enum, and same behaviour...
You can set the ShadowType to anything at the end it will still be Off

**Comment by amechtley** [comment]
Hi! Sorry no one ever replied to this issue. I'm hoping since it has been awhile that your issue was ultimately resolved. Using enum values on IComponentData should definitely work, but feel free to reopen this issue if you are still having this problem.
