### ISSUE TITLE
Dynamic Buffers : Dead Link

### ISSUE THREAD

**Issue by Opeth001** [Unity-Technologies/EntityComponentSystemSamples#80]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation/content/dynamic_buffers.md

**Comment by turadr** [comment]
Where did you find that link?
This is the correct address https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation/reference/dynamic_buffers.md .

**Comment by Opeth001** [comment]
Documentation/content/ecs_concepts look for ( See: Dynamic Buffers Link)

**Comment by wzl108** [comment]
------------------ 原始邮件 ------------------
发件人: "David"<notifications@github.com>;
发送时间: 2019年3月22日(星期五) 晚上9:00
收件人: "Unity-Technologies/EntityComponentSystemSamples"<EntityComponentSystemSamples@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [Unity-Technologies/EntityComponentSystemSamples] Dynamic Buffers: Dead Link (#80)




Closed #80.
