### ISSUE TITLE
For zero-sized components let AddComponent not fail if component exists

### ISSUE THREAD

**Issue by justonia** [Unity-Technologies/EntityComponentSystemSamples#83]
I am trying to be a good ECS citizen and utilize PostUpdateCommands as much as possible so my systems could be job-ifiable later on. I have numerous situations where I need to add a zero-sized flag component to indicate something has happened. 

However, there is no method available to add a component without triggering an error about it already existing. Since I cannot access any global state to check if it has been added in the update loop via PostUpdateCommands, I am forced into manually tracking this information. Alternatively I can use a write-allowed ComponentDataFromEntity to explicitly set/get the state of the flag component. This of course breaks any ability to use jobs and feels wrong.

I understand why AddComponent more than once on a regular >0 sized component is wrong, but for zero-sized flag components it feels like it makes a lot of sense to allow it.

**Comment by justonia** [comment]
As an example with pseudocode (I use a IBufferDataElement to queue collisions onto an entity):

    foreach collision in entity->DynamicBuffer<Collision>
        if IsProjectileImpact(collision) 
            PostUpdateCommands.AddComponent<HaveProjectileImpact>(hitEntity);

Since an entity can have more than one collision per-frame in this system, I don't have a way to test that hitEntity has already had a HaveProjectileImpact component set on it.

**Comment by justonia** [comment]
I have written an extension class to simplify this use case, it would be nice if there were some built in way of handling this:

[ComponentDataState.cs](https://github.com/justonia/UnityECSExtensions/blob/master/ComponentDataState/ComponentDataState.cs)

**Comment by justonia** [comment]
Preview 30 fixes this.

**Comment by Ph0t0nX** [comment]
The change log says "EntityCommandBuffer.AddComponent(Entity, ComponentType) no longer fails if the target entity already has the specified component."... is this for only tags or for any component?  And if it's for any component, what happens? Is the previous component replaced (essentially acting as an AddOrSetComponent() function), or is the component that's getting added just discarded and the old data remains?
