### ISSUE TITLE
Entity Debugger showing systems that are not involved in the running scene

### ISSUE THREAD

**Issue by shophk** [Unity-Technologies/EntityComponentSystemSamples#84]
Using the sample project, I had created a new scene, there is a default directional light and camera.

Played the scene, open Entity Debugger, I see UpdatePlayerHUD and some others in the debugger.
There is nothing in the scene, why are the systems running?

**Comment by EIZENHORN91** [comment]
Because it is not depend on scene or MB. If you not create system manually (marked [DisableAutoCreation]) or not create world manually, systems runs automatically (if they have [AlwaysUpdateSystem] or valid archetypes queried in this system)

**Comment by shophk** [comment]
Tested removing [AlwaysUpdateSystem] and the system did not appear in the debugger.

Not sure how to test DisableAutoCreation. Suggestions ?

Not sure how to test valid archetypes, but one clue showing in folder name Phyllotaxis, it has a CubeSpawnSystem running in the debugger but its unticked. I commented out all variables and the code in OnUpdate. There is nothing in the code that's running. Why is this It is still showing in the debugger?

Would you have any recommendations for showing me where you had gain this knowledge on ECS?

**Comment by shophk** [comment]
Tested DisableAutoCreation by adding it before class declaration of a ComponentSystem class. It worked, the class did not show up in the debugger.

I'm still trying to test valid archetypes, any suggestions?

**Comment by danielbrauer** [comment]
This is intended behaviour. It's based on ComponentSystemBase.ShouldRunSystem() in ComponentSystem.cs
