### ISSUE TITLE
Add IBufferElementData<T>

### ISSUE THREAD

**Issue by justonia** [Unity-Technologies/EntityComponentSystemSamples#85]
I suggest the addition of:

    public interface IBufferElementData<T> : IBufferElementData
        where T : struct
    {
    }

Since this allows extension methods like the following to be implemented safely:

    public static bool Remove<T, U>(this DynamicBuffer<T> buffer, U value)
        where T : struct, IBufferElementData<U>
        where U : struct, IEquatable<U>
    {
        var ubuffer = buffer.Reinterpret<U>();
        for (int i = 0; i < ubuffer.Length; i++)
        {
            if (buffer[i].Equals(value))
            {
                buffer.RemoveAt(i);
                return true;
            }
        }
        return false;
    }

I have done this manually in my project and it works very well.

**Comment by joeante** [comment]
I dont understand what this solves or how to use this based on the code example.

**Comment by justonia** [comment]
Here is a concrete example:

    [InternalBufferCapacity(4)]
    public struct EntityGroupBufferElement : IBufferElementData<Entity>
    {
        public static implicit operator Entity(EntityGroupBufferElement e) { return e.Value; }
        public static implicit operator EntityGroupBufferElement(Entity e) { return new EntityGroupBufferElement{ Value = e }; }

        public Entity Value;
    }

    [UpdateInGroup(typeof(UpdateGroupPostGameplay))]
    public class DeinitializeEntityGroupSystem : DeinitializeComponentDataSystem<EntityGroup>
    {
        [Inject] private BufferFromEntity<EntityGroupBufferElement> groupBuffers;

        protected override void Deinitialize(Entity entity, EntityGroup group)
        {
            if (!groupBuffers.Exists(entity)) {
                return;
            }

            DynamicBuffer<EntityGroupBufferElement> buffer = groupBuffers[entity];
            buffer.Remove(entity);    
        }
    }
