### ISSUE TITLE
ECS Unity Programing is VR ready?

### ISSUE THREAD

**Issue by castana1962** [Unity-Technologies/EntityComponentSystemSamples#86]
Hi All
Sorry for my ignorance but since I am interested in making VR projects for Oculus Go and Quest( without any PC or phone device), the biggest problem to build VR for these devices are the its Performance but I am not sure if ECS is VR ready, for it, Could you say me if ECS is a good programming option for VR developing? Thanks for your time
Best Regards
Alejandro

**Comment by joeante** [comment]
It has not been tested with VR yet.

**Comment by castana1962** [comment]
Mr Ante
First, thanks to answer me so fast.
On the other hand, Could I do another question about this topic?
How long could Unity test Unity ECS on VR? 
I ask you this because in the near future will be a lot changes in VR ( and I guess also that ECS), for it, Would it make any sense at the moment to prepare myself to program in ECS if one developer desire to use ECS in VR projects? 
Thanks for your time
Alejandro
