### ISSUE TITLE
 EntityComponentSystemSamples/Documentation/under_review/getting_started.md

### ISSUE THREAD

**Issue by mainsil** [Unity-Technologies/EntityComponentSystemSamples#89]
From:  EntityComponentSystemSamples/Documentation/under_review/getting_started.md,  Description under header "How does the Component System know about Rotator and Transform?" 

The section mentions in passing that there is a GameObjectEntity component that creates the entity, but does not tell the user how to accomplish this, nor does it even tell the user where they can learn how to accomplish this.  

Suggestion:
I think a complete but simple example (perhaps a rotating cube) would be immensely helpful and would ensure that the basics are covered.  As it currently stands, its hard to know where to begin.

**Comment by davidv-unity** [comment]
Hi, the current solution for this can be found in the Samples, what you're asking for sounds like the [conversion workflow](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Samples/Assets/HelloECS/HelloCube_01_ForEach/RotationSpeedProxy.cs) which transforms classic `GameObject`s into entity representation. Check out the [samples](https://github.com/Unity-Technologies/EntityComponentSystemSamples/tree/master/Samples/Assets) and go to the forums or reopen the issue if you need any further help. Kind Regards!
