### ISSUE TITLE
Burst compiler bug when modifying and returning struct value

### ISSUE THREAD

**Issue by xfxyjwf** [Unity-Technologies/EntityComponentSystemSamples#91]
Burst: 0.2.4-preview.39
Entities: 0.0.12-preview.21
Incremental Compiler: 0.0.42-preview.31
Unity Version: 2018.2.10f1

The following code does not produce correct result when burst is enabled:
```C#
    public struct Data : IComponentData
    {
        public MyVector Value1;
        public MyVector Value2;
    }
 
    public struct MyVector
    {
        public long X;
        public long Y;
        public long Z;
    }
 
    public static MyVector UpdateMyVector(MyVector value)
    {
        value = new MyVector
        {
            X = value.X + 5678,
        };
        return value;
    }
 
    public class TestBurstComponentSystem : JobComponentSystem
    {
        [BurstCompile]
        private struct Job : IJobProcessComponentData<Data>
        {
            public void Execute(ref Data data)
            {
                data.Value2 = UpdateMyVector(data.Value1);
            }
        }
 
        protected override JobHandle OnUpdate(JobHandle inputDeps)
        {
            return new Job().Schedule(this, inputDeps);
        }
    }
```
The UpdateMyVector method takes a MyVector struct as input and produces a MyVector struct as output. It's expected to return a new struct with modified X value while Y, Z being 0. When burst compiler is disabled, it works as expected. However, when burst compiler is enabled, the method returns the original input value as if the assignment doesn't exist.

I have put up a simple scene to reproduce this bug here:
https://github.com/xfxyjwf/burstbug

Open "Assets/Scenes/SampleScene.unity" and click play. At the center of the screen you are expected to see the number 5678, but when burst compiler is enabled you will see 0 instead. By toggling on/off burst jobs, you can see different values on the screen.

I have posted more detailed analysis of the bug on the forum:
https://forum.unity.com/threads/bug-burst-compiler-bug-when-modifying-and-returning-struct-value.598711/

**Comment by xoofx** [comment]
It has been fixed in burst in a subsequent version (don't remember which one), but you should be able to upgrade to `0.2.4-preview.45+`
