### ISSUE TITLE
Please consider removing AutomaticWorldBootstrap class when release

### ISSUE THREAD

**Issue by zhuchun** [Unity-Technologies/EntityComponentSystemSamples#92]
Hi, I come from Entitas background and a script called `AutomaticWorldBootstrap` confused me for such a while until I found this script and added `UNITY_DISABLE_AUTOMATIC_SYSTEM_BOOTSTRAP` to my scripting define symbols. 

This script indeed is a useful thing for people to play around and have fun with a few systems easier. However, I think it's important to let developers understand the workflow as a whole, including instantiate different worlds and then add systems to them manually. `AutomaticWorldBootstrap` in the package is black magic somewhat and will try to add all systems into a "Default World", which we usually don't do it in a real project. So please consider making it an optional choice.

**Comment by huhund** [comment]
I agree (just spamming here to bring the stats up for this thing :)  ).

**Comment by StewMcc** [comment]
`AutomaticWorldBootstrap` seems a much nicer flow for out of the box. Then overriding it once certain what systems to manually create. `UNITY_DISABLE_AUTOMATIC_SYSTEM_BOOTSTRAP` allows you to choose if you want it easily. With `DefaultWorldInitialization.Initialize` giving you a break down of how to do some of it.

Think just showing examples, of custom bootstraps, and wee bit better docs on it would be better. It does now at least mention briefly that this is running in the background.

**Comment by zhuchun** [comment]
It's good to know that now manual has mentioned these scripts. I still think it's a bad idea since beginners could ignore this point easily, I mean for people who never use ECS before, they need a robust workflow to work with. Enabling this by default only make sense for people who want to try something / make tutorials with a new project, it doesn't work for any other case, so we have to disable it every time before we want to make a serious.

In fact, I don't think it's a good practice for anyone. I know it may sound harsh, please bear with me ;)
People could write some debug/print system very often, but with the AutomaticWorldBootstrap, they have to delete/comment the script file, despite the fact that they would need to use it again later. That's not ideal.

**Comment by leethomason** [comment]
This code has evolved in the new versions, and there are new options, although I'm not sure your root concern is addressed. Since this isn't a bug in the samples, additional feedback is probably best provided in the Unity Forums.
