### ISSUE TITLE
Most samples removed in 0.0.21

### ISSUE THREAD

**Issue by Hemaolle** [Unity-Technologies/EntityComponentSystemSamples#98]
Before 0.0.21 there were about 10 samples in the respository, most of which have been removed with no explanation in ReleaseNotes.md. Gone are ChainExample, Dungeon, GalacticConquest, HierarchyExample etc.. We're now left with only BoidExample and a few HelloECS samples. This looks like a mistake. If it's been done on purpose, it would make sense to add a comment in ReleaseNotes.md or at least the forums.

**Comment by TheOddler** [comment]
Especially confusing is that the TwoStickShooter example is still mentioned in the readme, but was also removed.

**Comment by leethomason** [comment]
Closing external issue; may be too late to address, but tracked internally as 2281 to check.
